// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  **C1 `ingest_paths`** (§0.4.1) — the single §2.4 freeze point for every intake origin (drop / picker /
	 *  launch-arg / second-instance). This box (P2.22) authors the typed §0.4.1 wire CONTRACT — the
	 *  `{ paths, origin, collectingId, drainPending?, onScan } -> CollectedSet` door — so the generated
	 *  `bindings.ts` mirrors the C1 surface, pulling the whole `CollectedSet` graph + `IntakeOrigin` +
	 *  `ScanProgress` into the bindings as named types (the §0.6 defer-registration-to-the-consumer pattern).
	 *
	 *  - `paths` — the absolute FS paths to freeze (a drop / launch-arg / second-instance set; empty for the
	 *    `drain_pending` first-launch drain).
	 *  - `origin` — how the set entered intake (§7.8) — the §0.6 `IntakeOrigin`; a drop/launch-arg/second-instance
	 *    carries its origin here, while C2a's handler stamps `Picker` itself (§1.1).
	 *  - `collecting_id` — the frontend-generated ingest-scoped cancel handle (§0.4.4) so C13 `cancel_ingest`
	 *    can name this in-flight walk **before** C1's long await resolves (§1.1).
	 *  - `drain_pending` — `Some(true)` consumes the §7.8.1 first-launch `PendingIntake` buffer instead of
	 *    `paths` (mutually exclusive with a non-empty `paths`, §0.4.1); `None` / `Some(false)` = a normal intake.
	 *    Wire form `drainPending: boolean | null` (tauri-specta's `Option<bool>` arg form): the frontend passes
	 *    `null` for a normal intake, `true` to drain — `null` ≡ the spec's omittable `drainPending?` (serde maps
	 *    a missing/`null` `Option` arg to `None`).
	 *  - `on_scan` — the throttled scan-telemetry Channel (§0.4.2 `ScanProgress`, ≈2/s) driving the §5.2
	 *    *Collecting* "Scanning… N files" count; best-effort, monotonic, dies with the call. **Always passed**
	 *    (non-optional — see the forced-deviation note below); the frontend realises the §0.4.1 "optional" intent
	 *    by subscribing only for a long walk, never by omitting the argument.
	 *
	 *  [Build-Session-Entscheidung: P2.22] **Interface-shell body — the typed CONTRACT is the deliverable.**
	 *  P2.22 authors the §0.4.1 wire signature above so the generated `bindings.ts` carries the full C1 door;
	 *  the §2.4 freeze BODY is its own set of named, scheduled boxes — the §1.1 recursive walk → §1.2 detect →
	 *  §2.3 de-dup → §1.3 group freeze funnel (P2.62), the §0.4.4 `collecting_id` token registry (P2.45), the
	 *  `drain_pending` `PendingIntake` drain (P2.60), and the `on_scan` scan-telemetry pump (P2.69) — wired
	 *  end-to-end into this handler by P3.49 "Implement C1 `ingest_paths`" (the CSV→TSV walking-skeleton slice)
	 *  once those layers exist. This is the sanctioned compile-time interface-shell pattern (CLAUDE §5 / the P3
	 *  `crate::isolation` shells P4 expands), NOT a quiet deferral: a shell that performs no freeze collects
	 *  nothing, so it returns the §0.6 zero-collection `CollectedSet::Empty { skipped: [] }` (the genuinely-zero
	 *  case — cancelled dialog / drained-empty `PendingIntake` / all-hidden-filtered). The five contract args
	 *  are accepted so the wire signature is complete and bound to `_` to mark them shell-accepted (no
	 *  fabricated handling) until their named boxes consume them. The freeze funnel's own §0.7 module home is
	 *  P2.62's to fix (the §1.1/§2.4 freeze is not yet placed in the §0.7 tree), so P2.22 does not pre-create it.
	 *
	 *  [Build-Session-Entscheidung: P2.22] **`on_scan` is NON-OPTIONAL — a FORCED deviation from the §0.4.1
	 *  `onScan?` `[DECIDED]`.** tauri 2.11.3's `Channel<T>` is `!Deserialize` (it carries its own `CommandArg`
	 *  impl, but `Option<Channel<T>>` routes through the `CommandArg for D: Deserialize` blanket impl → E0277),
	 *  so an optional channel argument cannot compile. No behaviour is lost: the wire-form optionality is realised
	 *  by the frontend subscribing only for a long walk, never by omitting the arg. The rejected alternative was a
	 *  custom `OptionalChannel<T>` wrapper replicating undocumented `__CHANNEL__:N` internals (version-fragile).
	 *  §0.4.1 (C1 + the sibling C2a) / §0.4.2 + the README / plan / §05 mirrors are spec-synced non-optional in
	 *  THIS same commit (DoD item 2 — the forced deviation is reflected in the spec, not silently absorbed).
	 */
	ingestPaths: (paths: string[], origin: IntakeOrigin, collectingId: CollectingId, drainPending: boolean | null, onScan: Channel<ScanProgress>) => __TAURI_INVOKE<CollectedSet>("ingest_paths", { paths, origin, collectingId, drainPending, onScan }),
	/**
	 *  **C2a `pick_for_intake`** (§0.4.1) — the Rust-side `DialogExt` intake picker. This box (P2.23) authors the
	 *  typed §0.4.1 wire CONTRACT — the `{ kind, collectingId, onScan } -> CollectedSet` door — mirroring the C1
	 *  surface so the picker shares C1's freeze return and **no raw FS path ever reaches the WebView** (the WebView
	 *  only triggers the picker and receives the collected summary, §0.10 / §5.4).
	 *
	 *  - `kind` — the §0.6 `PickKind` (`Files` | `Folder`): open the native files-multiselect or the folder
	 *    dialog; a folder pick is recursively collected at the §1.1 freeze.
	 *  - `collecting_id` — the frontend-generated ingest-scoped cancel handle (§0.4.4), registered as the §1.1
	 *    token **before the dialog opens** so C13 `cancel_ingest` can trip the in-flight pick/walk (P2.70).
	 *  - `on_scan` — the throttled scan-telemetry Channel (§0.4.2 `ScanProgress`); **non-optional**, the *same*
	 *    `Channel<T>` `!Deserialize` forced deviation the C1 `ingest_paths` handler documents above — C2a takes it
	 *    identically (§0.4.1). The frontend always hands it and realises the "optional" intent by subscribing only
	 *    for a long walk, never by omitting the argument.
	 *
	 *  C2a carries **no `origin` field**: the picked set's origin is `Picker`, **stamped by this handler itself**
	 *  (P2.63), not supplied by the WebView (§1.1 / §5.4) — so a compromised WebView cannot forge the intake origin.
	 *
	 *  [Build-Session-Entscheidung: P2.23] **Interface-shell body — the typed CONTRACT is the deliverable.**
	 *  P2.23 authors the §0.4.1 wire signature above so the generated `bindings.ts` carries the full C2a door
	 *  (pulling `PickKind` into the bindings as a command-arg type). The native-dialog BODY is its own set of
	 *  named, scheduled boxes — the async/`spawn_blocking` `DialogExt` pick with the ingest token registered
	 *  before the dialog opens (P2.70), the token-drop-on-every-exit-branch rule (P2.71), and the `Picker`-origin
	 *  stamp + funnel into the C1 `ingest_paths` freeze (P2.63 / P2.62). This is the sanctioned compile-time
	 *  interface-shell pattern (CLAUDE §5 / the P3 `crate::isolation` shells P4 expands), NOT a quiet deferral: a
	 *  shell that opens no dialog and freezes nothing returns the §0.6 zero-collection `CollectedSet::Empty {
	 *  skipped: [] }` — which is **also the contract's genuine cancelled-dialog result** (a cancelled pick is a
	 *  clean no-op that returns `Empty`, no error, the UI stays Idle, §5.4). The three contract args are accepted
	 *  so the wire signature is complete and bound to `_` (no fabricated handling) until P2.70/P2.71/P2.63 consume
	 *  them.
	 */
	pickForIntake: (kind: PickKind, collectingId: CollectingId, onScan: Channel<ScanProgress>) => __TAURI_INVOKE<CollectedSet>("pick_for_intake", { kind, collectingId, onScan }),
	/**
	 *  **C13 `cancel_ingest`** (§0.4.1) — trips the ingest-scoped `CollectingId` token to cancel an in-flight
	 *  C1/C2a walk before its long await resolves (§1.1). Registered as the §0.4.1 interface shell (P2.21); the
	 *  full `{ collectingId } -> ()` contract is authored by P2.35. [Build-Session-Entscheidung: P2.21]
	 */
	cancelIngest: () => __TAURI_INVOKE<void>("cancel_ingest"),
	/**
	 *  **C2b `pick_destination`** (§0.4.1) — the Rust-side `DialogExt` destination-folder picker. This box (P2.24)
	 *  authors the typed §0.4.1 wire CONTRACT — the `{} -> Result<Option<PathBuf>, IpcError>` door — so the
	 *  generated `bindings.ts` carries the C2b surface. Unlike the C2a intake picker, the **one chosen `PathBuf` it
	 *  returns legitimately transits the WebView** into C5 `set_destination` (and then C6): it is a *write*
	 *  destination, not a source path, so it can never harm an original or read anything (§0.10 / §2.1 / §0.11 T2).
	 *  `Ok(None)` = the user cancelled — a clean no-op; the held C4/C5 destination is unchanged.
	 *
	 *  [Build-Session-Entscheidung: P2.24] **`Result<Option<PathBuf>, IpcError>` return — the §0.4 universal
	 *  error-shape rule.** §0.4 "Error shape" is categorical: *every* command returns `Result<T, IpcError>`. The
	 *  §0.4.1 table's `Option<PathBuf>` output column is the SUCCESS type `T`, wrapped in `Result<T, IpcError>` at
	 *  the handler — exactly as C1's `CollectedSet` column maps to `Result<CollectedSet, IpcError>`. So the three
	 *  boundary outcomes are: `Ok(Some(path))` = the user picked a folder; `Ok(None)` = the user cancelled (a clean
	 *  no-op, the §5.4 cancelled-picker result); `Err(IpcError)` = the native dialog subsystem genuinely failed (a
	 *  folder pick has no *user-facing* failure, but the boundary still honours the universal Result shape rather
	 *  than panicking across it, §0.4 "No command ever panics across the boundary"). The wire/TS callsite is
	 *  unchanged (`Result<T, E>` renders as `__TAURI_INVOKE<T>` + a thrown `IpcError`, like C1).
	 *
	 *  [Build-Session-Entscheidung: P2.24] **Interface-shell body — the typed CONTRACT is the deliverable.**
	 *  P2.24 authors the §0.4.1 wire signature; the native `DialogExt` folder-pick BODY (`app.dialog().file()
	 *  .pick_folder(..)`, opened async/`spawn_blocking` so it never blocks a Tokio worker, §7 app-shell) is wired
	 *  end-to-end at P3.56 — the DestinationBar, whose "Change destination" affordance drives C2b → C5 (P3.54 wires
	 *  the C2a *intake* picker, a distinct path; C2b is the *destination* picker). A native OS folder dialog is
	 *  **not unit-testable** (it needs a real OS dialog /
	 *  user interaction — the §6.6 walkthrough + the P9 E2E flow exercise it), so the testable P2 deliverable is
	 *  the typed contract; the shell returns `Ok(None)` — the genuine cancelled/no-pick result. This is the
	 *  sanctioned compile-time interface-shell pattern (CLAUDE §5 / the P3 `crate::isolation` shells P4 expands),
	 *  not a quiet deferral.
	 */
	pickDestination: () => __TAURI_INVOKE<string | null>("pick_destination"),
	/**
	 *  **C3 `get_targets`** (§0.4.1) — a pure function of the detected source type to the offered `Vec<Target>` +
	 *  the one pre-highlighted default + per-target lossy/availability/options model (§1.5/§1.6); no engine spawned.
	 *  This box (P2.25) authors the typed §0.4.1 wire CONTRACT — `{ collectedSetId } -> Result<TargetOffer,
	 *  IpcError>` (the §0.4 universal error shape) — so the generated `bindings.ts` carries the C3 door, pulling the
	 *  whole `TargetOffer` graph (`Target` / `TargetId` / `OptionValues` / …) into the bindings.
	 *
	 *  [Build-Session-Entscheidung: P2.25] **Shell returns `Err(IpcError{ kind: InternalError })` — the genuine
	 *  pre-registry "set not resolvable" outcome, NOT a stub.** `TargetOffer` has no zero value (§1.5: it carries
	 *  exactly one real `default_target`), so unlike C1/C2a (`CollectedSet::Empty`) / C2b (`Ok(None)`) there is no
	 *  `Ok(empty)` to return. Until the §0.4.4 collected-set registry (P2.44) + the §1.5/§1.6 target-resolution
	 *  logic land, **no** `collectedSetId` resolves — so the shell's honest result is exactly the `Err` the real
	 *  body returns for an unresolvable id: `Err(IpcError{ kind: ConversionErrorKind::InternalError, … })`.
	 *  `InternalError` is spec-grounded — the §2.13 catch-all, matching the §3.2 `PlanError` "can't compute the
	 *  plan" precedent (03-engines §3.2.1 `plan_encode` default `Err(PlanError{ InternalError })`).
	 *
	 *  Three things the named fill-boxes own (so this shell is a named, scheduled interface shell, CLAUDE §5):
	 *  (a) the §2.8 **message catalog** owns the FINAL wording — the `message` below is a PROVISIONAL neutral
	 *  English string — and must add a COMMAND-level string, because the current §2.8 catalog (02-guarantees
	 *  §2.8.2) is ITEM-scoped ("…this file was skipped"), which does not fit a command-level failure; (b) the
	 *  §0.4.4 registry resolve + the §0.6 SUCCESS path (a real `TargetOffer`) + any `kind` refinement belong to the
	 *  body box (P2.44+); (c) the `kind` is spelled with the CONCRETE `ConversionErrorKind`, NOT the `ErrorKind`
	 *  alias (the P2.19 convention against the rustc dead-code-EXPECTATION/alias interaction).
	 */
	getTargets: (collectedSetId: CollectedSetId) => __TAURI_INVOKE<TargetOffer>("get_targets", { collectedSetId }),
	/**
	 *  **C4 `plan_output`** (§0.4.1) — computes the §1.8 output plan (resolved destination directory, per-location
	 *  divert preview §2.7, §2.5 re-run prompt, §1.10 pre-flight verdict) that drives the "will save to…" line
	 *  before convert. This box (P2.26) authors the typed §0.4.1 wire CONTRACT — `{ collectedSetId, target,
	 *  options, destination } -> Result<OutputPlanPreview, IpcError>` (the §0.4 universal error shape) — so the
	 *  generated `bindings.ts` carries the C4 door, pulling the `OutputPlanPreview` graph (`DivertReason` /
	 *  `RerunPrompt` / `PreflightVerdict` / …) into the bindings.
	 *
	 *  [Build-Session-Entscheidung: P2.26] **Shell returns `Err(IpcError{ kind: InternalError })` — the same
	 *  owner-approved interface-shell pattern as C3 (P2.25).** `OutputPlanPreview` has no zero value (it carries a
	 *  resolved `final_dir_preview` + a `PreflightVerdict`), so there is no `Ok(empty)` to return; the genuine
	 *  pre-registry outcome (the §0.4.4 collected-set registry, P2.44, is not yet built) is exactly the `Err` the
	 *  real body returns for an unresolvable id: `Err(IpcError{ kind: ConversionErrorKind::InternalError, … })`
	 *  (§2.13 catch-all; the §3.2 `PlanError` `plan_encode` precedent). The named fill-boxes own the rest: (a) the
	 *  §2.8 catalog box owns the FINAL message (the string below is provisional) and must add a COMMAND-level
	 *  string (the §2.8 catalog is item-scoped); (b) the §0.4.4 registry resolve + the §1.8 `OutputPlan`
	 *  computation (divert / §2.5 re-run / §1.10 pre-flight) + the §0.6 SUCCESS path belong to the body box
	 *  (P2.44+); (c) `kind` is the CONCRETE `ConversionErrorKind`, not the `ErrorKind` alias (the P2.19 convention).
	 */
	planOutput: (collectedSetId: CollectedSetId, target: TargetId, options: OptionValues, destination: DestinationChoice) => __TAURI_INVOKE<OutputPlanPreview>("plan_output", { collectedSetId, target, options, destination }),
	/**
	 *  **C5 `set_destination`** (§0.4.1) — re-validates writability/divert and re-evaluates the
	 *  destination-dependent §2.14.4 pre-flight when the user changes the destination, carrying the §2.5 re-run
	 *  verdict through UNCHANGED (§2.5.1 — the v1 EquivKey has no destination component, so C5 never recomputes
	 *  `rerun`). This box (P2.27) authors the typed §0.4.1 wire CONTRACT — `{ collectedSetId, target, options,
	 *  destination } -> Result<DestinationResolved, IpcError>` (the §0.4 universal error shape; the SAME request
	 *  payload as C4 `plan_output`, the C4/C5 byte-identical-payload pair) — so the generated `bindings.ts` carries
	 *  the C5 door, pulling the `DestinationResolved` graph into the bindings.
	 *
	 *  [Build-Session-Entscheidung: P2.27] **Shell returns `Err(IpcError{ kind: InternalError })` — the same
	 *  owner-approved interface-shell pattern as C3/C4.** `DestinationResolved` has no zero value (it carries a
	 *  re-evaluated `PreflightVerdict`), so there is no `Ok(empty)`; the genuine pre-registry outcome (the §0.4.4
	 *  registry, P2.44, does not exist) is the `Err` the real body returns for an unresolvable id: `Err(IpcError{
	 *  kind: ConversionErrorKind::InternalError, … })` (§2.13 catch-all; the §3.2 `PlanError` precedent). The named
	 *  fill-boxes own the rest: (a) the §2.8 catalog box owns the FINAL message (the string below is provisional) +
	 *  must add a COMMAND-level string (the §2.8 catalog is item-scoped); (b) the §0.4.4 registry resolve + the
	 *  §1.8/§2.14.4 destination-change re-validation (re-eval pre-flight, carry `rerun` through) + the §0.6 SUCCESS
	 *  path belong to the body box (P2.44+) — the C4/C5 lifecycle asymmetry (C4 re-callable; C5 owns the
	 *  destination; C4 never overrides C5) is enforced by P2.28; (c) `kind` is the CONCRETE `ConversionErrorKind`,
	 *  not the `ErrorKind` alias (the P2.19 convention).
	 */
	setDestination: (collectedSetId: CollectedSetId, target: TargetId, options: OptionValues, destination: DestinationChoice) => __TAURI_INVOKE<DestinationResolved>("set_destination", { collectedSetId, target, options, destination }),
	/**
	 *  **C6 `start_conversion`** (§0.4.1) — mints the run's `RunId`, builds + enqueues the §1.9 batch from the
	 *  frozen collected set, spawns the §0.9 workers, and streams `ConversionEvent`s over the handed `onProgress`
	 *  Channel (the §0.4.2 E-series — `RunStarted` → per-item `ItemStarted`/`ItemProgress`/`ItemFinished` +
	 *  `BatchProgress` → terminal `RunFinished`); it returns immediately with the `RunId` (the run proceeds async,
	 *  the Channel carries all telemetry, §1.11). This box (P2.29) authors the typed §0.4.1 wire CONTRACT — the
	 *  `{ collectedSetId, target, options, destination, rerunDecision, onProgress } -> Result<RunId, IpcError>`
	 *  door (the §0.4 universal error shape) — so the generated `bindings.ts` mirrors the C6 surface and, **for
	 *  the first time, pulls the whole `ConversionEvent` graph onto the wire** (the P2.37 enum + its `RunStarted`/
	 *  `ItemStarted`/`ItemProgress`/`ItemFinished`/`BatchProgress` payloads + the `RunFinished` `RunResult` graph)
	 *  via the `onProgress` arg — the §0.6 defer-registration-to-the-consumer pattern (the `crate::orchestrator`
	 *  §0.4.2 note), exactly the `ScanProgress`-via-C1 precedent.
	 *
	 *  - `collected_set_id` — the frozen §0.4.4 collected-set handle (§2.4) the run is built from; resolved
	 *    against the §0.4.4 registry (P2.44) to the `CollectedSet::Single` whose items become the queue.
	 *  - `target` — the one whole-batch `TargetId` (§0.6 invariant 1 — one Target per Batch, never per item).
	 *  - `options` — the effective whole-batch `OptionValues` (§0.6 invariant 2 / §2.5).
	 *  - `destination` — **AUTHORITATIVE** (§0.4.1 C6 `[DECIDED]`): C4/C5 are plan/preview + revalidation only,
	 *    there is no separate server-side destination store — the value the UI passes here (the last C5-resolved
	 *    destination) is what the run writes to.
	 *  - `rerun_decision` — the §0.6 `RerunDecision` (the user's answer to a C4 `RerunPrompt`, §2.5): `Skip` (the
	 *    safe default — no new output for equivalent items) or `FreshCopy` (fresh numbered copies).
	 *  - `on_progress` — the run-telemetry `Channel<ConversionEvent>` (§0.4.2): ordered, run-scoped (dies with
	 *    the run — no cross-run leak, §1.11). Like C1's `onScan` it is **non-optional** (tauri's `Channel<T>` is
	 *    `!Deserialize`, so `Option<Channel<T>>` cannot be a command arg — the same forced shape the C1
	 *    `ingest_paths` handler documents; the §0.4.1 C6 row already specifies it non-optional).
	 *
	 *  [Build-Session-Entscheidung: P2.29] **Shell returns `Err(IpcError{ kind: InternalError })` — the same
	 *  owner-approved interface-shell pattern as C3/C4/C5 (P2.25/P2.26/P2.27).** `RunId` is a non-nil v4-UUID
	 *  newtype with no zero value (and no public constructor), so unlike C1/C2a (`CollectedSet::Empty`) / C2b
	 *  (`Ok(None)`) there is no `Ok(empty)` to return — and fabricating an `Ok(RunId)` would be a LIE (it would
	 *  claim a run started when nothing was enqueued and no `ConversionEvent` will ever fire on the Channel),
	 *  exactly the fabricated handling the interface-shell pattern forbids (CLAUDE §5). Until the §0.4.4
	 *  collected-set registry (P2.44) + the §1.9 queue / §0.9 workers land (P3.46), **no** `collectedSetId`
	 *  resolves — so the shell's honest result is exactly the `Err` the real body returns for an unresolvable id:
	 *  `Err(IpcError{ kind: ConversionErrorKind::InternalError, … })` (§2.13 catch-all; the §3.2 `PlanError`
	 *  `plan_encode` precedent C3/C4/C5 cite). The named fill-boxes own the rest: (a) the §2.8 catalog box owns
	 *  the FINAL message — the string below is a PROVISIONAL neutral English one — and must add a COMMAND-level
	 *  string (the §2.8 catalog is item-scoped); (b) the §0.4.4 registry resolve + the §1.9 queue build / §0.9
	 *  worker spawn / `ConversionEvent` emission + the §0.6 SUCCESS path (the minted `RunId`) belong to the body
	 *  box (P3.46), and the RunId mint-point (at C6 accept, NOT the §2.4 freeze — §7.1.2) is fixed by P2.48;
	 *  (c) `kind` is the CONCRETE `ConversionErrorKind`, not the `ErrorKind` alias (the P2.19 convention).
	 */
	startConversion: (collectedSetId: CollectedSetId, target: TargetId, options: OptionValues, destination: DestinationChoice, rerunDecision: RerunDecision, onProgress: Channel<ConversionEvent>) => __TAURI_INVOKE<RunId>("start_conversion", { collectedSetId, target, options, destination, rerunDecision, onProgress }),
	/**
	 *  **C7 `cancel_run`** (§0.4.1) — trips the `RunId`-indexed §0.4.4 cancellation token (`.cancel()` on the
	 *  run-registry `CancellationToken`, P2.42): finished items are kept, the in-progress item is discarded
	 *  cleanly (§2.1/§2.6), and the forceful engine kill is §1.7's mechanism (cooperative at the orchestrator
	 *  level, forceful at the engine level). This box (P2.30) authors the typed §0.4.1 wire CONTRACT — the
	 *  `{ runId } -> Result<(), IpcError>` door (the §0.4 universal error shape) — so the generated `bindings.ts`
	 *  mirrors the C7 surface.
	 *
	 *  - `run_id` — the §0.4.4 `RunId` (minted at C6) whose cancellation token to trip.
	 *
	 *  [Build-Session-Entscheidung: P2.30] **Shell returns `Ok(())` — the genuine no-op-cancel outcome, the
	 *  C1/C2a (`CollectedSet::Empty`) / C2b (`Ok(None)`) "zero-valued result" branch of the interface-shell
	 *  pattern, NOT the C3/C4/C5/C6 `Err(InternalError)` branch.** The split is principled: C3/C4/C5/C6 return
	 *  `Err` because their success type (`TargetOffer`/`OutputPlanPreview`/`DestinationResolved`/`RunId`) has **no
	 *  zero value**, so a pre-registry shell cannot honestly produce one. C7's success type is `()`, which **does**
	 *  have a zero value, and `cancel_run` is an **idempotent fire-and-forget side-effect**: it trips a token and
	 *  returns — `tokio_util` `CancellationToken::cancel()` on an unheld/already-cancelled token is a harmless
	 *  no-op, and a cancel of an already-finished run is the desired end-state ("not running" ⇒ effectively
	 *  cancelled, §0.4.4). So tripping *no* token (the shell has no run registry — P2.42 — yet) is genuinely
	 *  `Ok(())`, NOT a fabricated success: it claims nothing positive happened (unlike a fabricated C6 `Ok(RunId)`,
	 *  which would lie that a run started). The kill *outcome* is never C7's return — it is reported async via the
	 *  `ConversionEvent`/`RunResult` (§1.7/§1.12). The real registry resolve + `.cancel()` wiring lands at P2.42
	 *  (the `RunId` token registry) / P3.52 (the C7 cancel-wiring to the §1.1/P3.44 cooperative cancel); the
	 *  contract is unchanged by it (cancel stays `Ok(())`).
	 */
	cancelRun: (runId: RunId) => __TAURI_INVOKE<null>("cancel_run", { runId }),
	/**
	 *  **C8 `get_run_summary`** (§0.4.1) — the idempotent re-fetch of the retained §1.12 `RunResult` (the
	 *  end-of-batch summary: per-item outcome + output→source map + residue warnings + the open-folder roots),
	 *  also delivered once as the terminal `ConversionEvent::RunFinished`. C8 re-serves it from the §0.4.4
	 *  run-registry retention (the `RunResult` is held process-local until the next run starts or the app exits,
	 *  P2.43 — distinct from the cancellation token, which is dropped on `RunFinished`); the re-serve covers a
	 *  fresh listener attaching *after* the run has terminated (e.g. a WebView reload — v1 does not claim macOS
	 *  reload-mid-stream resilience, §0.4.4). This box (P2.31) authors the typed §0.4.1 wire CONTRACT — the
	 *  `{ runId } -> Result<RunResult, IpcError>` door (the §0.4 universal error shape) — so the generated
	 *  `bindings.ts` carries the C8 surface (the whole `RunResult` graph already mirrored via C6's `RunFinished`,
	 *  P2.29).
	 *
	 *  - `run_id` — the §0.4.4 `RunId` (minted at C6) whose retained summary to re-serve.
	 *
	 *  [Build-Session-Entscheidung: P2.31] **Shell returns `Err(IpcError{ kind: InternalError })` — the C3/C4/C5/
	 *  C6 interface-shell pattern (success type has no zero value), NOT the C7 `Ok(())` no-op branch.** `RunResult`
	 *  carries a real summary (items / totals / roots) and has **no zero value**, so — like `TargetOffer`/
	 *  `OutputPlanPreview`/`DestinationResolved`/`RunId`, unlike C7's `()` — there is no `Ok(empty)` to return, and
	 *  fabricating one would invent a summary for a run that never happened (CLAUDE §5). Until the §0.4.4
	 *  `RunResult` retention registry (P2.43) holds a terminal result, **no** `runId` resolves — so the shell's
	 *  honest result is exactly the `Err` the real body returns for an unresolvable / not-yet-finished id:
	 *  `Err(IpcError{ kind: ConversionErrorKind::InternalError, … })` (§2.13 catch-all; the §3.2 `PlanError`
	 *  precedent C3/C4/C5 cite). The named fill-boxes own the rest: (a) the §2.8 catalog box owns the FINAL message
	 *  — the string below is a PROVISIONAL neutral English one — and must add a COMMAND-level string (the §2.8
	 *  catalog is item-scoped); (b) the §0.4.4 retention resolve + the §1.12 `RunResult` projection (incl. the
	 *  pre-flight-skip projection + the batch-summary string) + the §0.6 SUCCESS path belong to the body box P3.50;
	 *  (c) `kind` is the CONCRETE `ConversionErrorKind`, not the `ErrorKind` alias (the P2.19 convention).
	 */
	getRunSummary: (runId: RunId) => __TAURI_INVOKE<RunResult>("get_run_summary", { runId }),
	/**
	 *  **C9 `open_path`** (§0.4.1) — the DoD "one-click open-folder / open-file" action: reveal or open an output
	 *  in the OS file manager / default app. The handler **validates `path` against the current §1.12 `RunResult`'s
	 *  recorded outputs (file-launch) or roots (folder-browse) — the §7.7.3 membership gate** — then calls the
	 *  opener plugin's `OpenerExt` internally (`reveal_item_in_dir` / `open_path`, §7.7.1); there is **no
	 *  `opener:*` WebView capability** (§0.10) — the Rust-side membership check, not a static scope, is the real
	 *  gate (§7.7.2: beside-source outputs routinely fall outside any OS-known root, so a glob scope could never
	 *  cover them). This box (P2.32) authors the typed §0.4.1 wire CONTRACT — the `{ kind, path } -> Result<(),
	 *  IpcError>` door (the §0.4 universal error shape) — so the generated `bindings.ts` mirrors the C9 surface
	 *  (pulling `OpenKind` into the bindings as a command-arg type).
	 *
	 *  - `kind` — the §0.6 `OpenKind` (`RevealInFolder` | `Folder` | `File`) selecting the §7.7.1 `OpenerExt` op:
	 *    reveal-with-select / open-containing-folder / open-file-in-default-app.
	 *  - `path` — the path to open; the §7.7.3 gate admits an *output file* for `File` and a run *root* for the
	 *    folder-browse kinds (`RevealInFolder`/`Folder`), refusing anything else (never a source, never an
	 *    arbitrary WebView path).
	 *
	 *  [Build-Session-Entscheidung: P2.32] **Shell returns `Err(IpcError{ kind: InternalError })` — the
	 *  C3/C4/C5/C6/C8 branch (the §7.7.3 gate refuses), NOT C7's `Ok(())` no-op branch.** Unlike C7's idempotent
	 *  fire-and-forget cancel (whose `()` zero value makes a tripped-nothing a genuine no-op success), C9 is a
	 *  **gated side-effect**: it opens `path` *only if* the §7.7.3 membership check passes, and a path not in the
	 *  set is **refused** (§7.7.2/§7.7.3 — "a path not in that set is refused and logged"). A refusal is an error,
	 *  not a successful no-op — returning `Ok(())` would falsely claim the open happened. The shell has no §1.12
	 *  `RunResult` to validate against (the §0.4.4 retention registry is P2.43), so **every** path fails the
	 *  membership check — exactly the `Err` the real body returns for a non-member path: `Err(IpcError{ kind:
	 *  ConversionErrorKind::InternalError, … })` (§2.13 catch-all; the §3.2 `PlanError` precedent C3/C4/C5 cite).
	 *  The named fill-boxes own the rest: (a) the §2.8 catalog box owns the FINAL message — the string below is a
	 *  PROVISIONAL neutral English one — and must add a COMMAND-level string (the §2.8 catalog is item-scoped); (b)
	 *  the §7.7.3 membership resolve (against the P2.43 `RunResult` retention) + the §7.7.1 `OpenerExt` reveal/open
	 *  call + the §7.5 refusal log + the §0.6 SUCCESS path (`Ok(())` on a validated open) belong to the body box
	 *  P3.51; (c) `kind` is the CONCRETE `ConversionErrorKind`, not the `ErrorKind` alias (the P2.19 convention).
	 */
	openPath: (kind: OpenKind, path: string) => __TAURI_INVOKE<null>("open_path", { kind, path }),
	/**
	 *  **C10 `open_project_page`** (§0.4.1) — the **only** permitted, user-initiated network action: opens a fixed
	 *  compiled-in canonical Ne-IA GitHub Releases URL in the default browser via `OpenerExt::open_url` (§7.6.2 /
	 *  §7.7.1). The WebView supplies **no URL** — the handler opens a compiled-in constant, eliminating any
	 *  URL-injection surface (§7.7.2); there is **no `opener:*` WebView capability** (§0.10), and no fetch/parse of
	 *  the page itself (§7.6.1 no phone-home). This box (P2.33) authors the typed §0.4.1 wire CONTRACT — the `{} ->
	 *  Result<(), IpcError>` door (the §0.4 universal error shape) — so the generated `bindings.ts` mirrors the C10
	 *  surface.
	 *
	 *  [Build-Session-Entscheidung: P2.33] **Shell returns `Err(IpcError{ kind: InternalError })` — the
	 *  deferred-body branch (C8/C9), NOT C7's `Ok(())` no-op.** C10 is a **side-effect** command (open a URL); its
	 *  success type `()` has only one meaning — `Ok(())` = "the URL was opened". The real `OpenerExt::open_url`
	 *  wiring is the body box **P2.104** (it adds the `AppHandle` + the compiled-in §7.6.2 URL constant); this
	 *  contract shell performs no open, so returning `Ok(())` would **falsely claim the page opened** — the
	 *  fabricated success CLAUDE §5 forbids. (Unlike C7's idempotent cancel, where tripping nothing genuinely *is*
	 *  the desired "not running" state, an un-opened URL is *not* a desired state, so the C7 `Ok(())` no-op branch
	 *  does not apply.) The honest shell outcome is the `Err` the operation yields when it cannot complete:
	 *  `Err(IpcError{ kind: ConversionErrorKind::InternalError, … })` (§2.13 catch-all; the §3.2 `PlanError`
	 *  precedent C3/C4/C5 cite). P2.104 replaces this with the real open — `Ok(())` on a successful shell-out,
	 *  `Err` on a genuine `OpenerExt` failure (no browser / OS error). The named fill-boxes own the rest: (a) the
	 *  §2.8 catalog box owns the FINAL message — the string below is a PROVISIONAL neutral English one — and must
	 *  add a COMMAND-level string (the §2.8 catalog is item-scoped); (b) the compiled-in §7.6.2 URL constant + the
	 *  §7.7.1 `OpenerExt::open_url` call + the `AppHandle` belong to the body box P2.104; (c) `kind` is the CONCRETE
	 *  `ConversionErrorKind`, not the `ErrorKind` alias (the P2.19 convention).
	 */
	openProjectPage: () => __TAURI_INVOKE<null>("open_project_page"),
	/**
	 *  **C11 `get_app_info`** (§0.4.1) — version, build id, platform, and the third-party-licenses / NOTICE data
	 *  for the §5.9 About screen (§7.2.3); no network. Registered as the §0.4.1 interface shell (P2.21); the full
	 *  `{} -> AppInfo` contract is authored by P2.34. [Build-Session-Entscheidung: P2.21]
	 */
	getAppInfo: () => __TAURI_INVOKE<void>("get_app_info"),
	/**
	 *  **C12 `get_engine_health`** (§0.4.1) — the cached §7.2.3 startup self-check (which bundled engines are
	 *  present/runnable, which §3.4 patent-gated targets are available), feeding §5.2. The `EngineHealth` type
	 *  is authored at P2.111 and the cache is populated by the P4 probe. Registered as the §0.4.1 interface
	 *  shell (P2.21); the full `{} -> EngineHealth` contract is wired by P2.113. [Build-Session-Entscheidung: P2.21]
	 */
	getEngineHealth: () => __TAURI_INVOKE<void>("get_engine_health"),
};

/* Types */
/**  A target's per-platform availability (§0.6 / §3.4 patent disposition, resolved per platform). */
export type Availability =
/**  Offered on this platform. */
"available" |
/**  Honestly unavailable here (§3.4 / §5.2) — `reason` names why. */
{ unavailable: {
	reason: string,
} };

/**
 *  `BatchProgress` (§0.4.2) — aggregate queue progress for the batch bar (§1.11).
 *
 *  [Build-Session-Entscheidung: P2.37.3] **`total` == `RunStarted.total_items` (queued-only) invariant.**
 *  `total` counts ONLY items that entered the §1.9 queue — the SAME queued-eligible denominator as
 *  `RunStarted.total_items` (P2.37.1), EXCLUDING pre-flight-skipped items. If `total` counted dropped-but-
 *  skipped items the bar could never reach 100%; skips are reconciled only at the §1.12 Summary. The equality
 *  `BatchProgress.total == RunStarted.total_items` is a §1.11 RUNTIME emission invariant the P3.46 conductor
 *  holds (both read the same `CollectedSet::Single.count`); P2.37.3 fixes the shared-`u32`-denominator field +
 *  its documented invariant. `done` is the completed-item numerator (also queued-only).
 */
export type BatchProgress = {
	runId: RunId,
	/**  Completed queued items (the numerator) — pre-flight skips excluded. */
	done: number,
	/**  QUEUED (eligible) items only — equals `RunStarted.total_items` (P2.37.3). */
	total: number,
};

/**
 *  A §2.6.4 cleanup-incomplete warning (§0.6) — one item whose partial could not be removed, naming WHERE
 *  the residue may remain so the summary never reports a clean success (§2.6 / §1.12).
 *
 *  [Build-Session-Entscheidung: P2.12] `Serialize` + `Type` (wire — embedded in `RunResult`), NO
 *  `Deserialize`; NOT `Copy` (owns a `PathBuf`). camelCase (`residuePath`). `item: ItemId` is the downward
 *  `orchestrator`→`domain` edge that co-homing this leaf here introduces (allowed).
 */
export type CleanupResidue = {
	/**  The item whose cleanup did not complete (§2.6.4) — the stable §0.6 `ItemId`. */
	item: ItemId,
	/**  Where the residue may remain (§2.6.4) — the only place the summary names a residue path. */
	residuePath: string,
};

/**
 *  A §1.4-owned structural-peek note surfaced in the §1.4 confirm summary (`CollectedSet::Single.notes`),
 *  PRODUCED by §1.2's bounded structural peek (step 4) — spreadsheets.md / images.md / audio.md own the
 *  per-format peek, §1.2 owns running it. The `kind` is a stable discriminant → the §5 label catalogue
 *  (§2.10); any value (sheet count, encoding, …) rides `detail`, NOT the variant. Never a pre-localised
 *  sentence (§5 localises the `kind`).
 *
 *  [Build-Session-Entscheidung: P2.6] Same wire policy as the sibling §0.6 types: derives `specta::Type`,
 *  `Serialize`, `Deserialize` and `#[serde(rename_all = "camelCase")]`; NOT `Copy` (owns an
 *  `Option<String>`). Registration is deferred to the C1 consumer (P2.22) with the rest of the
 *  CollectedSet graph.
 */
export type CollectedNote = {
	/**  The stable discriminant → the §5 label catalogue (§2.10). */
	kind: CollectedNoteKind,
	/**  The optional value (e.g. "3 sheets", "Windows-1252"). */
	detail: string | null,
};

/**
 *  The stable §1.4 note discriminant. The four typed variants each have a declared §1.2-step-4 producer;
 *  `Other` is a RESERVED forward-compatible catch-all emitted by no current (v1) engine — it carries its
 *  value in `CollectedNote.detail` and is never silently dropped.
 *
 *  [Build-Session-Entscheidung: P2.6] Fieldless wire enum like `SkipReason` / `ReadFailure`: `Copy` +
 *  `#[serde(rename_all = "camelCase")]` (`multipleSheets` / `animatedSource` / `multiSizeIcon` /
 *  `embeddedCoverArt` / `other`). No `Hash` (not a map key).
 */
export type CollectedNoteKind =
/**  spreadsheets.md: the source holds >1 sheet, only one is exported. */
"multipleSheets" |
/**  images.md: an animated source converted to a still target flattens. */
"animatedSource" |
/**  images.md: an ICO source holds >1 size. */
"multiSizeIcon" |
/**  audio.md: cover art present. */
"embeddedCoverArt" |
/**  Reserved forward-compatible catch-all — no v1 producer; the value rides `detail`. */
"other";

/**
 *  The frozen collected-set the C1 `ingest_paths` / C2a `pick_for_intake` commands return and the §1.4 /
 *  §5.2 confirm gate renders (§0.6 / §1.1 / §1.4). `Single` carries the FULL confirm-summary field set,
 *  so the wire type IS the §1.4 `CollectedSummary` (unified — the mandatory confirm gate gets a real IPC
 *  path); the §0.4.4 collected-set registry stores this payload + its roots keyed by `CollectedSetId`
 *  for C3–C6 to resolve. The five variants are the §1.3 grouping outcomes: exactly one eligible format
 *  (`Single`), 2+ eligible formats (`Mixed` → pre-flight refusal), a lone real-but-unsupported /
 *  lone-uncertain item (`Unsupported` / `Uncertain`), or nothing eligible (`Empty`, carrying the
 *  per-item skip reasons so §5.2 state-10 is specific, not reason-less).
 *
 *  [Build-Session-Entscheidung: P2.6] Wire policy mirrors the P2.2/P2.3/P2.15/P2.4/P2.5 §0.6 types:
 *  derives `specta::Type` + `Serialize`/`Deserialize`; externally-tagged with `#[serde(rename_all =
 *  "camelCase")]` at the enum level (variant tags `single`/`mixed`/`unsupported`/`uncertain`/`empty`) AND
 *  repeated on every field-bearing variant (serde does NOT cascade the enum-level rename to a
 *  struct-variant's FIELDS, so `Single` needs it for `total_bytes`/`encoding_hint`/`delimiter_hint` →
 *  `totalBytes`/`encodingHint`/`delimiterHint`). NOT `Copy` (owns `Vec`/`String`/`PathBuf`);
 *  `PartialEq`+`Eq` back the round-trip tests. No explicit specta registration here — the WHOLE
 *  CollectedSet graph (`DroppedItem`/`SkippedItem`/`CollectedNote`/…) auto-registers together via its C1
 *  consumer (P2.22), the established defer pattern; deriving `specta::Type` is what guarantees it mirrors
 *  to `bindings.ts` as a NAMED type (never `any`) once consumed, so an early registration would only emit
 *  a consumer-less type and churn `bindings.ts` ahead of its command.
 */
export type CollectedSet =
/**
 *  Exactly one eligible user-facing format across all readable items → a batch. Carries the full §1.4
 *  confirm-summary field set (it IS the `CollectedSummary` wire shape). `items` is the eligible
 *  filtered view + `skipped` the id-disjoint ineligible view over the §0.6-invariant-6 single id
 *  space; the §1.4 confirm-summary FIELDS are COMPUTED in P3.27/P3.28 — this box homes the wire TYPE.
 */
({ single: {
	id: CollectedSetId,
	instance: InstanceId,
	format: UserFacingFormat,
	items: DroppedItem[],
	/**
	 *  Shown in the confirm gate (§1.4). INVARIANT (§0.6): `count == items.len()`, set once at the
	 *  §1.1 freeze; kept separate so a wire consumer reading the tally never walks a 10k-file Vec (the
	 *  §6 property test asserts the equality so the duplication cannot drift).
	 */
	count: number,
	skipped: SkippedItem[],
	/**  Size hint for the §1.10 pre-flight (§1.4). */
	totalBytes: number,
	/**  The dropped root(s) → §2.7 subtree + open-folder. */
	roots: string[],
	/**  A detection-derived hint, e.g. CSV detected "Windows-1252" (per §04). */
	encodingHint: string | null,
	/**  A detection-derived hint, e.g. CSV/TSV detected ";" (per §04). */
	delimiterHint: string | null,
	/**
	 *  The §1.4-owned structural-peek notes (>1 sheet, animated source, …), PRODUCED by §1.2's
	 *  bounded peek — not invented here.
	 */
	notes: CollectedNote[],
} }) & { empty?: never; mixed?: never; uncertain?: never; unsupported?: never } |
/**
 *  Two or more distinct eligible source formats → the §1.3 hard pre-flight refusal; `found` lists
 *  each format with its count for the refusal message.
 */
({ mixed: {
	found: ([UserFacingFormat, number])[],
} }) & { empty?: never; single?: never; uncertain?: never; unsupported?: never } |
/**  A lone item that is a real type we identified but do not convert (§1.2); `detected` names it. */
({ unsupported: {
	detected: string,
} }) & { empty?: never; mixed?: never; single?: never; uncertain?: never } |
/**  A lone item we could not classify with confidence (§1.2); `note` carries the can't-tell text. */
({ uncertain: {
	note: string,
} }) & { empty?: never; mixed?: never; single?: never; unsupported?: never } |
/**
 *  Nothing eligible. `skipped` carries the per-item skip reasons (§1.3 projection from
 *  `EmptyReport.outcomes`) so §5.2 state-10 shows "N files, none convertible (M unreadable, …)"
 *  instead of a reason-less empty; `vec![]` for the genuinely-zero-items case (cancelled dialog /
 *  drained `PendingIntake` / all files hidden-filtered).
 */
({ empty: {
	skipped: SkippedItem[],
} }) & { mixed?: never; single?: never; uncertain?: never; unsupported?: never };

/**  The frozen collected-set handle the C3–C6 commands resolve (§0.4 / §0.6). */
export type CollectedSetId = string;

/**  An ingest-scoped cancellation handle, minted by the frontend before a `RunId` exists (§0.4 C13). */
export type CollectingId = string;

/**
 *  The §1.2 detection confidence — one name, two values, across §1.2 and §0.6 (the retired draft had a
 *  3-valued enum). `Low` is a first-class outcome on `Recognized`, NOT a silent extension fallback.
 */
export type Confidence =
/**  The signal is unambiguous. */
"high" |
/**  Recognized, but the signal is weak — surfaced honestly, never extension-guessed. */
"low";

/**
 *  The §2.8.1 conversion-outcome taxonomy — the single owner of the failure-kind set (§2.8 owns the set +
 *  their §2.8.2 strings; §0.4 owns the wire shape). Every engine / FS / detection failure maps to exactly
 *  one variant — there is no "other/unknown" that leaks a raw error (an unmapped fault becomes
 *  `InternalError`, §2.13). The §0.4.3 `ErrorKind` is its byte-identical wire mirror; see the `ErrorKind`
 *  alias below (§2.8.2 option 1: one enum, nothing to drift). Outbound-only (no `Deserialize`, see note above).
 */
export type ConversionErrorKind =
/**  Decoded but structurally invalid / truncated mid-stream. */
"corrupt" |
/**  0-byte or no decodable content. */
"empty" |
/**  Detection cannot identify the type at all (§1.2 uncertain/conflicting). */
"unrecognized" |
/**  Recognised but not an in-scope source (§1.2 "detected: X"). */
"unsupportedType" |
/**  In-scope source, but the target is not offered (defensive; the UI prevents it). */
"unsupportedPair" |
/**  Present at freeze, now unreadable: permission denied / exclusive lock. */
"unreadable" |
/**  Present at freeze, now missing: moved / deleted / removed media. */
"gone" |
/**  Encrypted / DRM source (PDF password, FairPlay, PlaysForSure) — ConvertIA never prompts/cracks. */
"passwordProtected" |
/**  Extract-audio asked of a source with no audio stream (cross-category.md / audio.md). */
"noAudioTrack" |
/**  Exceeds the §1.10 "too big" ceiling (pre-flight or mid-run). */
"tooBig" |
/**  `ENOSPC` while writing (§2.6 cleans the partial). */
"outOfDisk" |
/**  The output write/publish failed for a non-space reason (permission / IO at the destination, §2.1/§2.7). */
"writeFailed" |
/**  §2.2.3 — the name/extension would exceed the OS path limit (never truncated). */
"pathTooLong" |
/**  §2.1.2/§2.2 — the ~10,000-variant no-clobber cap was exhausted (a degenerate directory). */
"tooManyCollisions" |
/**  Subprocess killed by signal / nonzero abnormal exit (§1.7/§2.12). */
"engineCrash" |
/**  Exceeded the §1.7 timeout, killed (§2.12). */
"engineHang" |
/**  Subprocess clean nonzero exit with classifiable stderr (§3.5). */
"engineError" |
/**  Patent-gapped on this platform (§3.4) — honest "unavailable here". */
"platformUnavailable" |
/**
 *  macOS Gatekeeper quarantined a bundled engine sidecar so it can't spawn (§7.2.3) — distinct from
 *  `EngineMissing`/`BundleDamaged`.
 */
"quarantinedByOs" |
/**  The item failed AND its partial couldn't be removed (§2.6.4) — the only kind that names a residue path. */
"cleanupResidue" |
/**  Catch-all for an unexpected internal fault (§2.13); no trace shown. */
"internalError" |
/**  A required bundled engine is absent / unrunnable at startup (§7.2). */
"engineMissing" |
/**  The WebView core disconnected / failed to load (§2.13/§5.8). */
"webviewFault" |
/**  The app bundle / resources failed their integrity check (§7.2). */
"bundleDamaged" |
/**
 *  More than one source format in one drop — the §1.3 pre-flight refusal. Has NO IpcError producer:
 *  it is the `CollectedSet::Mixed` SUCCESS return from C1 (§0.6) driving the §5.2 state-9 refusal.
 *  Listed here ONLY to keep the enum byte-identical to the §0.4.3 wire mirror (no §2.13 producer).
 */
"mixedDrop";

/**
 *  The §0.4.2 run-telemetry event — the adjacently-tagged (`{ type, data }`) enum streamed over the C6
 *  `start_conversion` `onProgress: Channel<ConversionEvent>` (§0.4.2 / §1.11): ordered, throughput-friendly,
 *  run-scoped (dies with the run — no cross-run leak). `RunFinished` carries the §1.12 `RunResult` (mirrors C8).
 */
export type ConversionEvent =
/**  Batch accepted; the queue is built (§1.9). */
{ type: "runStarted"; data: RunStarted } |
/**  An item left `Pending` for `Running` (§1.9). */
{ type: "itemStarted"; data: ItemStarted } |
/**  Real per-item progress (§1.11 — never an indeterminate spinner). */
{ type: "itemProgress"; data: ItemProgress } |
/**  Terminal per item (§1.9). */
{ type: "itemFinished"; data: ItemFinished } |
/**  Aggregate queue progress for the batch bar (§1.11). */
{ type: "batchProgress"; data: BatchProgress } |
/**  Terminal for the run — the full §1.12 `RunResult` (mirrors C8). */
{ type: "runFinished"; data: RunResult };

/**  The closed set of cross-category operations (§0.6 / cross-category.md). */
export type CrossCatOp =
/**  Extract the audio track from a video. */
"extractAudio" |
/**  Render to an animated GIF. */
"toGif";

/**
 *  Where a batch's outputs are written (§0.6 / §2.7.1) — the C4/C5/C6 `destination` argument (§0.4.1).
 *  WebView-held, with no server-side store (§0.11 T2a): the no-harm machinery, not path provenance, is the bound.
 */
export type DestinationChoice =
/**
 *  Beside each source in place — the §2.7.1 default; folder layout is preserved for free and per-location
 *  divert (§2.7.2) still applies to any unwritable/ephemeral source.
 */
"besideSource" |
/**
 *  A single user-chosen root under which the dropped-selection-relative subtree is re-created (§2.7.1, not
 *  flattened). A re-validated HINT, never a guarantee — §2.7.2 / §7.4.1 re-check writability + divert at use time.
 */
{ chosenRoot: string };

/**
 *  The C5 `set_destination` return (§0.6 / §1.8 / §2.14.4) — the re-validated destination after the user
 *  changes it. Homed in `crate::orchestrator` (embeds `preflight: PreflightVerdict` → transitively
 *  references `crate::outcome`, §0.7 ‡).
 *
 *  [Build-Session-Entscheidung: P2.11] `Serialize` + `Type`, NO `Deserialize` (embeds the Serialize-only
 *  `PreflightVerdict`); NOT `Copy`. camelCase.
 */
export type DestinationResolved = {
	/**  The (now chosen) destination (§0.6 / §2.7). */
	destination: DestinationChoice,
	/**  The recomputed per-location divert for the new destination (§2.7.2); `None` = no divert. */
	diverted: DivertReason | null,
	/**
	 *  The preflight RE-EVALUATED for the new destination volume (§2.14.4 free-space) so the UI's held C4
	 *  verdict never goes stale (§1.8).
	 */
	preflight: PreflightVerdict,
	/**
	 *  CARRIED THROUGH UNCHANGED from the C4 verdict — in v1 the §2.5 EquivKey has no destination
	 *  component, so re-run is destination-INDEPENDENT (§2.5.1); C5 re-evaluates ONLY `preflight`, never
	 *  recomputes `rerun`.
	 */
	rerun: RerunPrompt | null,
};

/**
 *  The single canonical §1.2 detection outcome `[DECIDED]`. There is no separate
 *  `DetectedFormat`/`DetectionConfidence` pair — the earlier 3-valued confidence enum and the
 *  `Option<UserFacingFormat>` that collapsed Empty-vs-Unreadable are retired. An ineligible outcome
 *  (`UnsupportedType`/`Uncertain`/`Empty`/`Unreadable`) is NEVER offered a target list and NEVER
 *  silently extension-fallback-guessed (SSOT *Recognize files by content*); it is surfaced
 *  eligible=false with the exact §2.8 plain-language string (the projection to a `SkipReason` is P2.16).
 */
export type DetectionOutcome =
/**
 *  A supported v1 source type, with confidence. `dims` carries the header-derived raster
 *  width/height (JPEG SOF, PNG IHDR, …), read by the §1.2 bounded structural peek — `None` for a
 *  non-raster type or where the header lacks them. It is the input the §1.10 cheap per-pixel size
 *  estimate consumes, so the estimate never needs a decode.
 */
({ recognized: {
	format: UserFacingFormat,
	confidence: Confidence,
	dims: [number, number] | null,
} }) & { uncertain?: never; unreadable?: never; unsupportedType?: never } |
/**
 *  A real type we identified but do not convert (SSOT "can't convert this type — detected: X").
 *  `detected` carries the named type for the message.
 */
({ unsupportedType: {
	detected: string,
} }) & { recognized?: never; uncertain?: never; unreadable?: never } |
/**
 *  Sniffed but the signal is contradictory or below threshold — name the best guess (or that we
 *  can't tell) and decline clearly (SSOT). `Low` confidence never silently falls back to the
 *  extension; a genuinely ambiguous file lands here, not in `Recognized`.
 */
({ uncertain: {
	bestGuess: string | null,
} }) & { recognized?: never; unreadable?: never; unsupportedType?: never } |
/**  0-byte / no bytes to read. */
"empty" |
/**  Could not read the bytes at all — `reason` distinguishes gone / locked / permission / other. */
({ unreadable: {
	reason: ReadFailure,
} }) & { recognized?: never; uncertain?: never; unsupportedType?: never };

/**
 *  Why a single source's output was diverted away from its intended location (§0.6 / §2.7.2). Carried by the
 *  P2.11 wire DTOs (`OutputPlanPreview`/`DestinationResolved`); on `OutputPlan`, `None` = beside-source (no divert).
 */
export type DivertReason =
/**  The intended location could not be written — read-only USB / network share / restricted folder (§2.7.2). */
"unwritable" |
/**
 *  The intended location is a known-ephemeral OS temp place the OS may silently purge (§2.7.2) — writing a
 *  result there would lose the user's output.
 */
"ephemeral" |
/**
 *  The destination filesystem accepts a create but offers NO atomic create-only no-clobber publish primitive
 *  (FAT/exFAT-class: neither `RENAME_NOREPLACE`-class no-replace rename NOR hardlinks). Unix-only — Windows'
 *  `MoveFileExW` is create-only on FAT/exFAT (§2.7.2 / §2.14.2).
 */
"noAtomicPublish";

/**
 *  One eligible item in the §1.1-frozen collected set — the per-item record the pipeline carries
 *  from freeze through conversion (§0.6 / §1.2). It is a wire type: it reaches the WebView as
 *  `CollectedSet::Single.items` (P2.6), but on the wire `raw_path` is **DISPLAY-ONLY** — the §5.3
 *  BatchSummary derives sample basenames from the first few `items[].raw_path`, and the WebView
 *  NEVER re-submits it as intake. The only intake funnels are C1 (paths the native drop/launch
 *  gave) and C2a (paths the Rust-opened picker gave), both Rust-side; a frozen set's `raw_path`
 *  travelling back for display does not let the WebView feed an arbitrary path into a conversion
 *  (the §0.6 `raw_path` SCOPE `[DECIDED]` note). The §2.4 freeze de-duplicates by RESOLVED IDENTITY
 *  on `resolved_path` (owned by §2.3), so two paths reaching one real file are one `DroppedItem`.
 *
 *  [Build-Session-Entscheidung: P2.4] Wire policy mirrors the P2.2/P2.3/P2.15 §0.6 types: derives
 *  `specta::Type` + `Serialize`/`Deserialize` with `#[serde(rename_all = "camelCase")]` so it mirrors
 *  to `bindings.ts` in the §0.6 camelCase wire form (`raw_path` → `rawPath`, `resolved_path` →
 *  `resolvedPath`, `size_bytes` → `sizeBytes`). NOT `Copy` (it owns two `PathBuf`s + a `String`-bearing
 *  `DetectionOutcome`); NOT `Hash` (it is not a map key — the de-dup is by resolved identity on
 *  `resolved_path`, §2.3, not by hashing the whole record). `PartialEq`+`Eq` back the round-trip + the
 *  §6 property tests (`DetectionOutcome` is `Eq`, so the struct is). No explicit specta-`Builder`
 *  registration here — the same choice P2.15 made: the type auto-registers when its consuming command
 *  (C1's `CollectedSet` return, P2.22) is wired, so an early registration would emit it with no consumer.
 */
export type DroppedItem = {
	/**
	 *  The §0.6 invariant-6 freeze-assigned id over the SINGLE id space (eligible + skipped). `items`
	 *  is a filtered VIEW that is NEVER re-indexed from 0, so each `DroppedItem` carries its own
	 *  `ItemId` (its position in `items` is NOT its id). Symmetric with `SkippedItem.item` (P2.5);
	 *  `ConversionJob.item` denormalizes it (P2.10).
	 */
	item: ItemId,
	/**  The path as the OS handed it at drop/pick time. DISPLAY-ONLY on the wire (see the type doc). */
	rawPath: string,
	/**
	 *  The symlink/junction/alias-resolved real path (§2.3) — the identity the §2.4 freeze
	 *  de-duplicates on and the path the engine is ultimately pointed at.
	 */
	resolvedPath: string,
	/**  Size in bytes of the resolved file, recorded at the §2.4 freeze. */
	sizeBytes: number,
	/**
	 *  The single canonical §1.2 detection verdict for this item — §1.2 OWNS the type (P2.15), §0.6
	 *  references it. NOT a separate `DetectedFormat` (that earlier name is retired).
	 */
	detected: DetectionOutcome,
};

/**  A named preset choice inside an `Enum` option (e.g. MP3 "High"/"Standard"/"Small"), §1.6. */
export type EnumChoice = {
	/**  The stable id stored in `OptionValue::Enum` (never localised). */
	value: string,
	/**  The §5 UI-chrome label for the choice. */
	label: LabelKey,
};

/**  One per app launch (§7.1). */
export type InstanceId = string;

/**
 *  How a set of paths entered intake (§0.6 / §7.8). Every source is routed through the single §7.8.1
 *  funnel into the §1.1 intake state machine, so the §2.4 freeze + §1.3 one-batch rules apply
 *  identically regardless of origin. `Drop`/`Picker` reach C1/C2a directly; only `LaunchArg` and
 *  `SecondInstance` ever travel on the `app://intake` event (§0.4.2 / §7.8.1).
 *
 *  [Build-Session-Entscheidung: P2.2] `#[serde(rename_all = "camelCase")]` matches the established
 *  §0.6 wire-enum casing (the sibling `ErrorKind`/`IpcError` wire types, §0.4.3): the variants
 *  serialize as `drop`/`picker`/`launchArg`/`secondInstance`. `Serialize`+`Deserialize` because the
 *  origin crosses IPC both inbound (the C1 `ingest_paths` arg, §0.4.1) and outbound (the `app://intake`
 *  payload, §7.8.1); `Copy`/`Eq` are free for a fieldless enum. (`Hash` is omitted — not a map key.)
 */
export type IntakeOrigin =
/**  Files dropped on the drop area — the §1.1 primary intake; reaches C1 `ingest_paths` directly. */
"drop" |
/**  Files chosen via the OS file picker (C2a `pick_for_intake`); reaches C1 directly. */
"picker" |
/**
 *  Files passed at first launch (the desktop-entry `%F`/`%U` expansion, the Windows first-launch
 *  `argv`, or the macOS first-launch `RunEvent::Opened`), drained through the §7.8.1
 *  buffer-then-replay once the WebView is ready (§7.8).
 */
"launchArg" |
/**
 *  Files handed to the already-running instance by a second launch — the §7.1.1 single-instance
 *  `argv`/cwd callback, or the macOS `RunEvent::Opened` while already running (§7.8).
 */
"secondInstance";

/**
 *  The §0.4.3 authoritative error shape — every command's `Err` and every `ItemOutcome::Failed.error` is
 *  this ONE shape (§0.4.3 / §2.8). Homed in `crate::outcome` (the §2.8 taxonomy → §0.4.3 IpcError mirror
 *  module, §0.7). OUTBOUND-ONLY (a `Result` `Err` / `ItemOutcome::Failed.error` return, never deserialized
 *  from the WebView) — so `Serialize` + `Type`, NO `Deserialize` (mirroring the outbound-only
 *  `ConversionErrorKind`/`ErrorKind`, P2.18). `message` is the §2.8.2 pre-localised plain English string
 *  (NEVER a stack trace / raw engine stderr, SSOT *no stack traces*); the §2.8 message CATALOG that
 *  produces it is a separate later box.
 *
 *  [Build-Session-Entscheidung: P2.19] `kind` is typed with the CONCRETE `ConversionErrorKind`, NOT the
 *  §0.4.3-named `ErrorKind` ALIAS (`pub type ErrorKind = ConversionErrorKind`, P2.18) — the SAME type, but
 *  referencing the forward-declared alias from this (production-dead-until-consumed) struct trips the rustc
 *  dead-code-EXPECTATION/alias interaction with this module's forward-declaration suppression; the concrete
 *  spelling avoids it (the P2.10 `JobState::Failed` / P2.9 `OutputPlan.job` precedent). specta resolves the
 *  alias to the concrete type regardless, so the mirrored wire/bindings type is `ConversionErrorKind`
 *  either way.
 *
 *  [Build-Session-Entscheidung: P2.19] Registered in the P1.25 type registry (§0.4.3 / §2.8: "both
 *  IpcError and ErrorKind derive specta::Type and are registered in collect_types![]") so
 *  `ItemOutcome::Failed.error` + every command `Err` mirror to `bindings.ts` as the named `IpcError`
 *  rather than `any`; registering `IpcError` pulls its referenced `ConversionErrorKind` into the export as
 *  a named type too (the §2.8.2 deferred-to-its-consumer registration, P2.18). Derive set: `Serialize` +
 *  `Type` (the §0.4.3 wire-required pair) + `Debug, Clone, PartialEq, Eq` (ergonomics + the serialize-pin
 *  test); NOT `Copy` (owns a `String` + two `PathBuf`s); NO `Deserialize` (outbound-only). camelCase wire.
 */
export type IpcError = {
	/**  The stable machine code from the §2.8 taxonomy — drives the UI branching + i18n. */
	kind: ConversionErrorKind,
	/**  The §2.8.2 pre-localised plain-language English message; NEVER a stack trace / raw engine stderr. */
	message: string,
	/**  The optional path the error concerns (for the §1.12 summary's output→source map). */
	path: string | null,
	/**
	 *  The optional residue location when §2.6 cleanup could not complete — so the item is never reported
	 *  as a clean success.
	 */
	residue: string | null,
};

/**
 *  `ItemFinished` (§0.4.2) — terminal per item (§1.9). Carries the §0.6 `ItemOutcome` projection.
 *
 *  [Build-Session-Entscheidung: P2.37.4] **Pre-flight-skip emission policy — no LIVE `ItemFinished{Skipped}`.**
 *  Pre-flight-skipped items (§1.1/§1.3 — detection-ineligible; they never enter the §1.9 queue) are NOT emitted
 *  as a live `ItemFinished` carrying `ItemOutcome::Skipped`; they appear ONLY in the terminal
 *  `RunFinished → RunResult.items` projection (§1.12). `ItemOutcome::Skipped` is RESERVED for that terminal
 *  path (it is not dead wire code — it carries the projected pre-flight skips + any mid-run cooperative skip),
 *  so the conductor emits no live `ItemStarted`/`ItemFinished{Skipped}` for a freeze-time skip. The
 *  `ItemFinished.outcome` field structurally CAN carry `Skipped` (the SAME shared `ItemOutcome` type as the
 *  terminal `RunResult.items`), so the policy is a §1.9/§1.12 RUNTIME emission rule the P3.46 conductor honors,
 *  NOT a type-level prohibition; P2.37.4 fixes the documented policy + the structural enabler.
 */
export type ItemFinished = {
	runId: RunId,
	itemId: ItemId,
	/**  The terminal §0.6 outcome (`Succeeded | Failed | Skipped | Cancelled`). */
	outcome: ItemOutcome,
};

/**  Stable item index within a run (§0.6). */
export type ItemId = number;

/**
 *  The terminal per-item outcome carried by the LIVE §0.4.2 `ItemFinished` event (§0.6) — the richer
 *  terminal projection the UI applies as each item finishes, distinct from the summary's `JobState`.
 *  `Failed` carries the full §0.4.3 `IpcError` (kind + message + path + residue) the live row needs;
 *  `Succeeded` the published output path; `Skipped` the §0.6 `SkipReason`; `Cancelled` is payload-free.
 *
 *  [Build-Session-Entscheidung: P2.12] `Serialize` + `Type` (wire — the `ItemFinished` payload), NO
 *  `Deserialize` (outbound-only — embeds the outbound-only `IpcError`); NOT `Copy` (`Failed` owns an
 *  `IpcError` with `String`/`PathBuf`). Externally tagged with `#[serde(rename_all = "camelCase")]` (the
 *  §0.6 wire-enum convention) + per-struct-variant `rename_all` (serde does not cascade the enum-level
 *  rename to a variant's fields, so `Succeeded`'s `output_path` → `outputPath` needs its own, cf.
 *  `CollectedSet`). Variant order matches §0.6 exactly.
 */
export type ItemOutcome =
/**  Converted + atomically published (§2.1) — carries the final output path. */
({ succeeded: {
	outputPath: string,
} }) & { failed?: never; skipped?: never } |
/**  A named §2.8 failure — carries the full §0.4.3 `IpcError` the live row renders. */
({ failed: {
	error: IpcError,
} }) & { skipped?: never; succeeded?: never } |
/**  A pre-flight detection-ineligible item (§1.2/§1.3) — carries the §0.6 `SkipReason` (skip ≠ fail). */
({ skipped: {
	reason: SkipReason,
} }) & { failed?: never; succeeded?: never } |
/**  User-cancelled; nothing written (§1.7/§1.11). Not an `ErrorKind` (§0.4.3 note) — payload-free. */
"cancelled";

/**  `ItemProgress` (§0.4.2) — real per-item progress (§1.11; SSOT *not an indeterminate spinner*). */
export type ItemProgress = {
	runId: RunId,
	itemId: ItemId,
	/**
	 *  `0.0..=1.0`; `None` ONLY where truly indeterminate (LibreOffice, §1.11 — the frontend synthesises a
	 *  staged determinate-looking bar from `stage` there).
	 */
	fraction: number | null,
	/**  The §0.6/§1.11 coarse stage (`Spawning | Decoding | Encoding | Writing`). */
	stage: JobStage,
};

/**
 *  One per-item row of the §1.12 summary (§0.6) — its source path (for output→source mapping), its terminal
 *  `JobState`, the output path (`Some` only when `Succeeded`), and the resolved surfaced line.
 *
 *  [Build-Session-Entscheidung: P2.12] `Serialize` + `Type` (wire — embedded in `RunResult`), NO
 *  `Deserialize`; NOT `Copy` (owns `PathBuf`/`OutcomeMsg`). camelCase. `state: JobState` is what forces
 *  `JobState` to be a wire type (see its doc) — the summary's per-item state, distinct from the live
 *  `ItemFinished`'s `ItemOutcome`.
 */
export type ItemResult = {
	/**  The source path this row is for — the output→source mapping anchor (SSOT *How It Feels* 7). */
	source: string,
	/**
	 *  The terminal §1.9 lifecycle state for this item (§0.6) — at `RunFinished` always a terminal variant
	 *  (`Succeeded`/`Failed`/`Skipped`/`Cancelled`).
	 */
	state: JobState,
	/**  The published output path — `Some(..)` ONLY when `state == Succeeded` (§1.12); `None` otherwise. */
	output: string | null,
	/**
	 *  The resolved, ready-to-show §2.8 failure / §2.9 lossy / §1.1 skip line (§2.8.2 `OutcomeMsg`); `None`
	 *  for a plain success with no lossy note.
	 */
	reason: OutcomeMsg | null,
};

/**  `ItemStarted` (§0.4.2) — an item left `Pending` for `Running` (§1.9). */
export type ItemStarted = {
	runId: RunId,
	itemId: ItemId,
	/**  The frozen resolved source path being converted (§2.4). */
	sourcePath: string,
	/**  The whole-batch target (§0.6 invariant 1) this item converts to. */
	target: TargetId,
};

/**
 *  The coarse per-item progress stage (§0.6), carried by the §0.4.2 `ItemProgress` Channel event; §1.11
 *  owns the per-engine semantics, this is the shared/wire enum NAME. Homed in `crate::domain` (the tier-3
 *  leaf) because it references NO `crate::outcome` type (§0.7 ‡, P2.10) — unlike its sibling lifecycle
 *  types `Batch`/`ConversionJob`/`JobState`, which reference the §2.8 kind and so are homed in
 *  `crate::orchestrator` (tier 1).
 *
 *  [Build-Session-Entscheidung: P2.10] A WIRE enum: derives `specta::Type` (so `ItemProgress.stage`
 *  mirrors to `bindings.ts` as a named type, never `any`) + `Serialize` with `#[serde(rename_all =
 *  "camelCase")]` (`spawning`/`decoding`/`encoding`/`writing`). OUTBOUND-ONLY — the `ItemProgress` Channel
 *  event is sent Rust→WebView and never deserialized inbound, so NO `Deserialize` (mirroring the
 *  outbound-only `ScanProgress` (P2.7) + `ConversionErrorKind` (P2.18) derive choice). `Copy` (fieldless).
 *  Registration is DEFERRED to the C6 `ConversionEvent`/`ItemProgress` consumer (P2.37), the established
 *  P2.2-P2.9 defer pattern (the no-`any` guarantee is the `Type` derive, not an early consumer-less
 *  registration that would churn `bindings.ts` ahead of its event).
 */
export type JobStage =
/**  The engine subprocess is being spawned (§1.7/§2.12). */
"spawning" |
/**  The source is being decoded. */
"decoding" |
/**  The target is being encoded. */
"encoding" |
/**  The output is being written + atomically published (§2.1). */
"writing";

/**
 *  The §1.9 job-lifecycle state (§0.6) — §1.9 owns the TRANSITIONS between these variants; this is the
 *  canonical state TYPE the orchestrator stores on each `ConversionJob` AND surfaces per-item in the §1.12
 *  `RunResult.items[].state` summary. `Failed` carries the §2.8 kind, NOT a full `IpcError` (the wire
 *  `IpcError` is assembled from the kind + path + message at the §1.12 projection — storing just the kind
 *  keeps `JobState` cheap and serde-stable, §0.6).
 *
 *  [Build-Session-Entscheidung: P2.12] `JobState` IS a WIRE type — it derives `Serialize` + `specta::Type`
 *  (added here, correcting the P2.10 "internal, not a wire type" note). The spec puts it on the wire: §0.6
 *  `ItemResult.state: JobState` is carried inside `RunResult`, which §0.4.2 emits as `RunFinished(RunResult)`
 *  and the C8 return, and §0.6's own JobState comment calls it "serde-stable". This is DISTINCT from the LIVE
 *  per-item `ItemFinished` event, which carries the richer terminal `ItemOutcome` projection — the §1.12
 *  summary's per-item state is `JobState`, the live terminal event is `ItemOutcome`; BOTH cross the wire,
 *  for two different surfaces (P2.10's note conflated them). OUTBOUND-ONLY (no `Deserialize` — it is only
 *  ever sent Rust→WebView in the summary, never deserialized), mirroring the §2.8 kinds it carries.
 *  Externally tagged with `#[serde(rename_all = "camelCase")]` (the §0.6 wire-enum convention, cf.
 *  `DetectionOutcome`/`CollectedSet`): unit variants serialize as `"pending"`…`"cancelled"`, the newtype
 *  variants as `{"failed":"corrupt"}` / `{"skipped":"empty"}`.
 *
 *  [Build-Session-Entscheidung: P2.10] `Failed` is spelled with the CONCRETE `crate::outcome::
 *  ConversionErrorKind`, NOT the §0.6/§1.9-named `ErrorKind` ALIAS (`pub type ErrorKind =
 *  ConversionErrorKind`, P2.18) — it is the SAME type, but referencing the still-forward-declared
 *  `ErrorKind` alias from this (production-dead) type trips the rustc dead-code lint-EXPECTATION
 *  interaction with `crate::outcome`'s forward-declaration suppression (type aliases have incomplete
 *  dead-code-expectation support); the concrete spelling avoids it with no semantic change — exactly the
 *  P2.9 `OutputPlan.job: ItemId`-not-`JobId` resolution. specta resolves the alias to the same wire type.
 *
 *  [Build-Session-Entscheidung: P2.10/P2.12] `Debug, Clone, Copy, PartialEq, Eq` — `Copy` because both
 *  payloads (`ConversionErrorKind` + `SkipReason`) are `Copy` fieldless enums, so the state is a cheap value
 *  to move through the lifecycle; PLUS `Serialize` + `Type` (P2.12, the wire pair above). Variant order
 *  matches §0.6 exactly.
 */
export type JobState =
/**  Queued, not started (§1.9). */
"pending" |
/**  The engine has been invoked (§1.7). */
"running" |
/**  Output verified + atomically published (§2.1). */
"succeeded" |
/**
 *  A named §2.8 failure kind; nothing was written for it (§2.1). The §1.9 Running→Failed transition
 *  maps the internal kind to the wire kind via `ErrorKind::from` in `crate::run` (§2.8.2).
 */
({ failed: ConversionErrorKind }) & { skipped?: never } |
/**
 *  A detection-ineligible pre-flight item (§1.2/§1.3) — set at `Batch` construction, never queued,
 *  terminal (§1.9). Carries the §0.6 `SkipReason` copied directly from the `SkippedItem`.
 */
({ skipped: SkipReason }) & { failed?: never } |
/**  User cancel; nothing written for it (§1.7/§1.11). */
"cancelled";

/**
 *  A UI-chrome label key (§1.6 / §5 / §2.10) — §5 resolves it to a localised string. NOT a user-facing
 *  string itself; keeps the domain model i18n-free (§2.8/§2.9 own surfaced strings). Bare-string wire form.
 */
export type LabelKey = string;

/**
 *  The predictable-loss kind keyed by the §2.9.1 catalog (the canonical English note lives in §2.9; this
 *  is the ONE canonical name). Carried by `Target.lossy: Option<LossyKind>` (the §1.5 offer-time SINGLE
 *  marker) and `OutcomeMsg::Lossy { kind }` (§2.8, P2.20). The §2.9.2 CO-APPLYING set (2-3 kinds rendered
 *  together at §5.7) is a SEPARATE render-time computation (P4.65), NOT this single offer marker — §1.5
 *  owns the wire field as `Option<LossyKind>`, §2.9.2/§5.7 own the rendered set (the box-note-flagged
 *  §1.5-vs-§2.9.2 distinction, surfaced for owner escalation and confirmed an offer-vs-render layering).
 *
 *  [Derived-Assumption: P2.8 — LossyKind wire form is snake_case (`image_lossy_codec`), derived from the
 *  §2.9.1 catalog + the 04-formats cross-references (images/spreadsheets/documents/presentations/audio),
 *  which all name the kind in snake_case as a stable cross-referenced catalog key. §0.4.3's camelCase rule
 *  governs FIELD names; LossyKind is a fieldless discriminant enum, so its snake_case is a per-catalog
 *  discriminant casing, not a §0.4.3 deviation.]
 *
 *  [Build-Session-Entscheidung: P2.8] Registered standalone in the P1.25 type registry — §2.8.2 (line
 *  1261) EXPLICITLY mandates LossyKind (with OutcomeMsg/ConversionErrorKind) derive `specta::Type` + be
 *  registered in `collect_types![]` so `Target.lossy` / `OutcomeMsg.kind` never generate as `any`. Derives
 *  both `Serialize` + `Deserialize` (Copy, fieldless) so it round-trips AND embeds in the round-trippable
 *  `Target`; the §2.8 sibling enums are Serialize-only, but LossyKind's embedding in a `Deserialize`
 *  `Target` requires `Deserialize` here. Variant order matches the §2.9.1 catalog (audio_downmix last).
 */
export type LossyKind =
/**  `→ JPG/WEBP(lossy)/HEIC/AVIF` from any source (images.md). */
"image_lossy_codec" |
/**  `→ GIF` 256-colour reduction (images.md). */
"image_palette" |
/**  `→ ICO` multi-size icon assembly (images.md). */
"image_downscale" |
/**  alpha source `→ JPG/BMP` transparency flatten (images.md). */
"image_alpha_flatten" |
/**  animated source `→` still target (images.md). */
"image_animation_flatten" |
/**  `SVG → raster` (images.md). */
"image_svg_raster" |
/**  `DOCX/DOC/ODT/RTF/MD → PDF` and `XLSX/XLS/ODS → PDF` reflow (documents.md / spreadsheets.md). */
"doc_pdf_reflow" |
/**  `PDF → TXT` (documents.md). */
"doc_pdf_to_text" |
/**  `HTML → PDF` (documents.md). */
"doc_html_render" |
/**  `* → TXT` from rich sources (documents.md). */
"doc_to_text" |
/**  `* → MD/RTF` from rich sources (documents.md). */
"doc_simplified" |
/**  `XLSX/XLS/ODS → CSV/TSV` (spreadsheets.md). */
"sheet_to_delimited" |
/**  `* → XLS` legacy format (spreadsheets.md). */
"xls_legacy_limits" |
/**  `CSV/TSV → workbook/CSV` non-Unicode encoding (spreadsheets.md). */
"text_encoding_narrowed" |
/**  `PPTX/PPT/ODP → PDF` (presentations.md). */
"slides_to_pdf_flatten" |
/**  ODF↔MS office round-trip + slide re-layout (presentations.md). */
"office_roundtrip_approx" |
/**  `PPTX → PPT` legacy downgrade (presentations.md). */
"pptx_to_ppt_legacy" |
/**  `→ MP3/AAC/M4A/OGG/OPUS` (audio.md). */
"audio_lossy_target" |
/**  lossy source `→` lossy target (audio.md). */
"audio_transcode" |
/**  lossy source `→` lossless target (audio.md). */
"audio_lossy_origin" |
/**  >16-bit source `→` default 16-bit WAV/AIFF (audio.md). */
"audio_bitdepth" |
/**  `→ AAC`, partly WAV/AIFF — tags dropped (audio.md). */
"audio_tags_dropped" |
/**  re-encode disposition (video.md / cross-cat). */
"video_reencode" |
/**  WEBM(alpha) `→ MP4/H.264` (video.md). */
"video_alpha_lost" |
/**  image/ASS subs `→ MP4` (video.md). */
"video_subs_dropped" |
/**  `video → GIF` cross-category, unconditional (cross-category.md). */
"video_to_gif" |
/**  surround forced to stereo by codec (rare; audio.md). */
"audio_downmix";

/**  The C9 `open_path` `kind` arg (§0.4.1 / §7.7) — how to surface an output path. Inbound. */
export type OpenKind =
/**  Open the containing folder. */
"folder" |
/**  Open the file itself in its default app. */
"file" |
/**  Reveal the file within its folder (highlight it). */
"revealInFolder";

/**
 *  A declared option for a (source, target) pair (§1.6), supplied by the registry (concrete values in
 *  04-formats). The pipeline renders/collects these generically; the §1.4 options panel (P4.64) renders
 *  it and P5-P7 register concrete declarations against it.
 */
export type OptionDecl = {
	/**  The stable machine key. */
	key: OptionKey,
	/**  The §5 UI-chrome label key (§2.10). */
	label: LabelKey,
	/**  Basic vs Advanced surface tier. */
	surface: Surface,
	/**  The control shape + bounds/choices. */
	kind: OptionKind,
	/**  The no-decision default (from 04-formats). */
	default: OptionValue,
};

/**
 *  A stable machine key for an option (e.g. "quality", "fps", "lossless"), §1.6. Used as the
 *  `OptionValues` BTreeMap key and in the §2.5 EquivKey canonicalisation, so it is a stable ASCII slug,
 *  never a UI label. Derives `Ord` for its BTreeMap-key role; serializes transparently as a bare string.
 */
export type OptionKey = string;

/**  The shape of an option control (§1.6). Externally tagged; the payload carries the bounds/choices. */
export type OptionKind =
/**  A bounded integer (quality / CRF / compression level) with a range + optional display unit. */
({ intRange: {
	min: number,
	max: number,
	step: number,
	unit: Unit | null,
} }) & { enum?: never; size?: never } |
/**  A small named preset set mapping to engine flags. */
({ enum: {
	choices: EnumChoice[],
} }) & { intRange?: never; size?: never } |
/**  A boolean toggle (lossless on/off, progressive, BOM). */
"toggle" |
/**  A pixel/size value (SVG width, GIF width). */
({ size: {
	min: number,
	max: number,
} }) & { enum?: never; intRange?: never } |
/**  A colour (flatten background) — picker; default usually white. */
"color";

/**
 *  One concrete, fully-resolved option value (§1.6). INVARIANT (§1.6): every variant is JSON-serialisable
 *  and round-trips through the §2.5 canonical form; no floats (no NaN/Inf), colours as `#RRGGBB(AA)`.
 */
export type OptionValue =
/**  An `IntRange` / `Size` resolved value. */
({ int: number }) & { bool?: never; color?: never; enum?: never } |
/**  A `Toggle` value. */
({ bool: boolean }) & { color?: never; enum?: never; int?: never } |
/**  The chosen `EnumChoice.value` (the stable id, not the label). */
({ enum: string }) & { bool?: never; color?: never; int?: never } |
/**  A `#RRGGBB` / `#RRGGBBAA` colour. */
({ color: string }) & { bool?: never; enum?: never; int?: never };

/**
 *  The effective, fully-defaulted-plus-overrides option set for a batch (§0.6; == §1.6 `EffectiveOptions`).
 *  The ONE wire/domain name for the resolved values, keyed by the stable `OptionKey`. Serializes
 *  transparently as its inner map (a JSON object keyed by the `OptionKey` slug strings).
 */
export type OptionValues = { [key in OptionKey]: OptionValue };

/**
 *  The §2.8.2 surfaced per-item outcome — the *resolved, ready-to-show* line for one item, carried by the
 *  §0.6 `ItemResult.reason: Option<OutcomeMsg>` (which rides the `RunFinished` Channel payload + the C8
 *  return, §0.4.2/§1.12). It is **either** a §2.8 failure, a §2.9 lossy note, **or** a §1.1/§1.3 pre-flight
 *  skip — three distinct variants so a consumer pattern-matching `OutcomeMsg` can tell skip from fail WITHOUT
 *  also reading `ItemResult.state` (§0.6 keeps `Skipped`/`Failed` distinct, §1.12 `Totals` counts them
 *  separately — "must not be conflated"). Each variant carries the stable discriminant (`kind`/`reason`) so
 *  §5 may re-localise (§2.10) AND the resolved English `text` (the §2.8.2 catalog row / §2.9.1 note with its
 *  `{x}` substitutions already applied), so the §5.3 Summary needs no second lookup.
 *
 *  [Build-Session-Entscheidung: P2.20] OUTBOUND-ONLY (it crosses the boundary inside the outbound
 *  `RunResult`/`ItemResult`, never deserialized from the WebView) — `Serialize` + `Type` (the §2.8.2
 *  wire-required pair so `ItemResult.reason` mirrors as the named `OutcomeMsg`, not `any`) + `Debug, Clone,
 *  PartialEq, Eq` (ergonomics + the serialize-pin tests); NOT `Copy` (owns a `String` per variant); NO
 *  `Deserialize` (outbound-only, mirroring `IpcError`/`ConversionErrorKind`). Adjacently tagged
 *  (`tag = "type", content = "data"`) so each variant is a discriminated `{ type, data }` object on the wire.
 *  Registered in the P1.25 type registry (§2.8.2 line 1261 mandate), which pulls its referenced `SkipReason`
 *  (+ the already-registered `ConversionErrorKind`/`LossyKind`) into the export as named types. `Failure.kind`
 *  is spelled with the CONCRETE `ConversionErrorKind`, NOT the `ErrorKind` alias — mirroring the P2.19
 *  `IpcError.kind` decision (referencing the forward-declared alias from a production-dead item trips the
 *  rustc dead-code-expectation/alias interaction; specta resolves the alias to the same wire type regardless).
 */
export type OutcomeMsg =
/**
 *  A §2.8 conversion FAILURE (the item entered the queue and failed) — `kind` is the §2.8.1 taxonomy code,
 *  `text` the §2.8.2 catalog row with its substitutions applied.
 */
{ type: "failure"; data: {
	kind: ConversionErrorKind,
	text: string,
} } |
/**
 *  A §2.9 predictable-LOSS note on an otherwise-successful conversion — `kind` is the §2.9.1 catalog key,
 *  `text` the §2.9.1 note.
 */
{ type: "lossy"; data: {
	kind: LossyKind,
	text: string,
} } |
/**
 *  A §1.1/§1.3 pre-flight SKIP (a detection-ineligible item that never entered the queue, projected into
 *  `RunResult.items` at run-end, §1.12) — `reason` is the §0.6 `SkipReason`. A skip rides THIS skip-shaped
 *  variant, NOT `Failure`, so skip ≠ fail at the type level (§1.12).
 */
{ type: "skipped"; data: {
	reason: SkipReason,
	text: string,
} };

/**
 *  The C4 `plan_output` return (§0.6 / §1.8) — drives the "will save to…" line shown before convert. Homed
 *  in `crate::orchestrator` (it embeds `preflight: PreflightVerdict` → transitively references
 *  `crate::outcome`, §0.7 ‡).
 *
 *  [Build-Session-Entscheidung: P2.11] `Serialize` + `Type`, NO `Deserialize` (embeds the Serialize-only
 *  `PreflightVerdict`); NOT `Copy` (owns a `PathBuf`). camelCase wire form.
 */
export type OutputPlanPreview = {
	/**  The collected set this preview is for (the §0.4.4 registry key). */
	set: CollectedSetId,
	/**
	 *  The resolved destination DIRECTORY shown before convert (§1.8 / §2.7) — directory-based, never a
	 *  pre-baked final file path (the numbered name is resolved at §2.1 write time).
	 */
	finalDirPreview: string,
	/**  `Some(reason)` if a per-location divert was previewed (§2.7.2); `None` = beside-source / no divert. */
	diverted: DivertReason | null,
	/**
	 *  `Some(..)` if the §2.5 in-session ledger detected an equivalent prior run (the one batch-level
	 *  prompt's data); `None` = no re-run prompt.
	 */
	rerun: RerunPrompt | null,
	/**  The §1.10 size/space estimate + any up-front whole-batch fail. */
	preflight: PreflightVerdict,
};

/**  The C2a `pick_for_intake` `kind` arg (§0.4.1) — pick files or a folder. Inbound (WebView → Rust). */
export type PickKind =
/**  Pick one or more files. */
"files" |
/**  Pick a folder (recursively collected at the §1.1 freeze). */
"folder";

/**
 *  The §1.10 resource pre-flight verdict surfaced before convert (§0.6 / §1.10) — the size/space estimate
 *  plus any whole-batch up-front "too big" / "won't fit" fail. Carried by the C4/C5 `OutputPlanPreview` /
 *  `DestinationResolved` returns. Homed in `crate::orchestrator` (it references `crate::outcome` DIRECTLY
 *  via `up_front_fail`).
 *
 *  [Build-Session-Entscheidung: P2.11] `Serialize` + `Type` (a wire type), NO `Deserialize` (its
 *  `up_front_fail: Option<ConversionErrorKind>` is outbound-only — `ConversionErrorKind`/`ErrorKind` have
 *  no `Deserialize`, P2.18); NOT `Copy` (struct convention). `up_front_fail` spells the concrete
 *  `ConversionErrorKind` (the `ErrorKind` alias's underlying type) against the P2.10 alias trap.
 */
export type PreflightVerdict = {
	/**  Estimated total output + kind-1 publish-temp footprint across the batch (§1.10 / §2.14.1). */
	estTotalOutputBytes: number,
	/**  Estimated total kind-2 engine-working scratch footprint across the batch (§1.10 / §2.14.2). */
	estTotalScratchBytes: number,
	/**
	 *  `Some(TooBig | OutOfDisk)` ONLY for the WHOLE-BATCH doomed case (the §5.2 disable-Convert-wholesale
	 *  flag — per-physical-volume / aggregate, §1.10). A PER-ITEM too-big / out-of-disk is NOT carried here
	 *  — it is enforced at write time as that item's `Failed(TooBig|OutOfDisk)` while the batch continues
	 *  (§1.10 / §1.11). `None` = the batch is not up-front doomed.
	 */
	upFrontFail: ConversionErrorKind | null,
};

/**
 *  Why a file's bytes could not be read at freeze/detect time (§1.2). Owned here; the §2.8 taxonomy
 *  projects these to a plain-language string. Distinct from a conversion-time failure (that is the §2.8
 *  `ConversionErrorKind`, mirrored as `ErrorKind` in P2.18).
 */
export type ReadFailure =
/**  Gone between drop and freeze (§2.4). */
"notFound" |
/**  The OS denied the read. */
"permissionDenied" |
/**  Exclusively locked by another process (esp. Windows). */
"locked" |
/**  Any other OS read error. */
"ioError";

/**
 *  The C6 `start_conversion` re-run decision (§0.6 / §2.5) — the user's answer to the `RerunPrompt`.
 *  INBOUND (WebView → Rust, a C6 input), so it derives `Deserialize`. `Skip` is the SAFE DEFAULT (produce
 *  no new output for the equivalent items); `FreshCopy` makes fresh numbered copies (§2.5). Any change to
 *  target/settings is a new conversion using ordinary numbering, not a re-run decision.
 *
 *  [Build-Session-Entscheidung: P2.11] Round-trippable (`Serialize` + `Deserialize`) because it crosses IPC
 *  inbound (the C6 arg); `Copy` (fieldless enum); camelCase wire form (`skip` / `freshCopy`).
 */
export type RerunDecision =
/**  The safe default — produce no new output for the equivalent items (§2.5). */
"skip" |
/**  Make fresh numbered copies of the equivalent items (§2.5). */
"freshCopy";

/**
 *  The one batch-level §2.5 re-run prompt's data (§0.6 / §2.5) — surfaced once per batch when the
 *  in-session ledger detects an equivalent prior run (same resolved source + target + effective settings,
 *  §2.5.1). OUTBOUND-ONLY: it is carried inside the C4/C5 `OutputPlanPreview` / `DestinationResolved`
 *  returns (Rust→WebView), never sent inbound — so `Serialize` + `Type` with NO `Deserialize` (mirroring
 *  the outbound-only `ScanProgress` (P2.7) derive choice). The user's RESPONSE is the separate inbound
 *  `RerunDecision`.
 *
 *  [Build-Session-Entscheidung: P2.11] NOT `Copy` (the established struct convention, like `ScanProgress`);
 *  `PartialEq` + `Eq` back the embedding `OutputPlanPreview` / `DestinationResolved` equality + the
 *  serialize pin. camelCase renames `equivalent_count` → `equivalentCount`.
 */
export type RerunPrompt = {
	/**  How many items in the batch are flagged equivalent to a prior in-session run (§2.5). */
	equivalentCount: number,
};

/**  One per `start_conversion` run (§0.4 C6 / §7.1). */
export type RunId = string;

/**
 *  The §1.12 end-of-batch summary (§0.6) — emitted as §0.4.2 `RunFinished(RunResult)` when every job has
 *  left `Pending`/`Running`, and idempotently re-served by C8 `get_run_summary` after a WebView reload
 *  (§0.4.4 run-registry retention). It is the §5.3 `ResultSummary`'s single source: per-item outcome +
 *  output→source map + residue warnings + the open-folder roots.
 *
 *  [Build-Session-Entscheidung: P2.12] `Serialize` + `Type` (wire), NO `Deserialize`; NOT `Copy` (owns
 *  `Vec`/`PathBuf` fields). camelCase wire form (`collectedSetId`/`runId`/`cleanupIncomplete`/`commonRoot`/
 *  `divertRoot`).
 */
export type RunResult = {
	/**
	 *  The frozen collected-set this run summarises — `Batch.id` IS a `CollectedSetId` (§1.12), tying the
	 *  summary back to its §0.4.4 collected-set registry entry.
	 */
	collectedSetId: CollectedSetId,
	/**  The run this summary is for (§7.1) — minted at C6 `start_conversion`. */
	runId: RunId,
	/**
	 *  Per-item outcome + output→source mapping (§1.12). INCLUDES the freeze-time pre-flight `SkippedItem`s
	 *  (`CollectedSet::Single.skipped`) projected as `ItemResult { state: Skipped(reason), output: None,
	 *  reason: Some(OutcomeMsg::Skipped{ reason, .. }) }` — the skip rides the skip-shaped `OutcomeMsg`
	 *  variant (§2.8), NOT `Failure`, so skip ≠ fail at the type level (§1.12); counted in `totals.skipped`.
	 */
	items: ItemResult[],
	/**  The succeeded / failed / cancelled / skipped tally (§1.12). */
	totals: Totals,
	/**
	 *  The §2.6 cleanup-incomplete warnings — items whose partial could not be removed, so the run is never
	 *  reported as a clean success (§2.6.4). Empty when every cleanup completed.
	 */
	cleanupIncomplete: CleanupResidue[],
	/**
	 *  The "open folder" target for the BESIDE-SOURCE outputs — the dropped-selection common ancestor
	 *  (§2.7 / §7.7.3).
	 */
	commonRoot: string,
	/**
	 *  `Some(Downloads/Documents/chosen)` when ANY item was diverted (§2.7.3) — a single `PathBuf` cannot
	 *  carry both the beside-source and divert roots, so the divert root is its own field; `None` when no
	 *  item diverted. Both are §7.7.3 open-folder targets; per-item diverted outputs are also reachable via
	 *  `ItemResult.output` (C9 `open_path`, `kind = RevealInFolder`).
	 */
	divertRoot: string | null,
};

/**
 *  `RunStarted` (§0.4.2) — the batch was accepted and the §1.9 queue built.
 *
 *  [Build-Session-Entscheidung: P2.37.1] **`total_items` = QUEUED (eligible) items only.** It equals the §1.3
 *  `CollectedSet::Single.count` (i.e. `items.len()` — NOT the internal `Grouping::Single.members`, never on the
 *  §0.6 wire), EXCLUDING pre-flight-skipped items (§1.1/§1.3, which never enter the §1.9 queue). It is the
 *  `BatchProgress.total` denominator (P2.37.3), so a skipped item never holds the bar below 100% — skips are
 *  reconciled only at the §1.12 Summary. The "= count" equality is a §1.9 RUNTIME emission rule the P3.46
 *  conductor enforces when it builds the queue; P2.37.1 fixes the FIELD + its documented denominator contract.
 *
 *  [Build-Session-Entscheidung: P2.37.2] **`will_reencode` is a non-optional `bool`, always definite.** A
 *  conservative source-container→target worst-case flag (§2.9.2 — re-encode *possible* ⇒ `true`), decided from
 *  the (source-container, target) pair BEFORE any `ffprobe` (inner codecs unknown at emit). The §2.9.2 emission
 *  rule is that the core ALWAYS emits a definite value — `false` for non-video / non-applicable batches, never
 *  omitted — so the Rust field is a plain `bool` (NOT `Option<bool>`) and the generated wire type is a
 *  non-optional `willReencode: boolean` with no third `undefined` state. The real per-item disposition is
 *  resolved at convert-time (§3.5); the §1.12 summary reflects the actual outcome.
 */
export type RunStarted = {
	/**  The run this telemetry belongs to (§0.4.4). */
	runId: RunId,
	/**  QUEUED (eligible) items only — the P2.37.1 denominator (see the struct doc). */
	totalItems: number,
	/**  The conservative worst-case re-encode flag — always a definite `bool` (P2.37.2). */
	willReencode: boolean,
};

/**
 *  The C1 `ingest_paths` `onScan` Channel payload (§0.4.2) — a throttled (~2/s, coalesced) live count of
 *  files seen during the §1.1 recursive walk + §1.2 detection, so the §5.2 Collecting state can show
 *  "Scanning… N files so far". Best-effort, monotonic, dies with the C1 call.
 *
 *  [Build-Session-Entscheidung: P2.7] Honors the §0.6 literal's deliberate OUTBOUND-ONLY derive set
 *  (`#[derive(Clone, Serialize, specta::Type)]`): the frontend RECEIVES this Channel payload but never
 *  sends it, so no `Deserialize` (and no `PartialEq`/`Eq` — the contract is the serialized form, not a
 *  round-trip; `Debug` is a benign ergonomic add). `specta::Type` is MANDATORY (§0.6: a
 *  `Channel<ScanProgress>` without it is `any` in `bindings.ts`). camelCase for module uniformity (a
 *  no-op on the single-word `scanned`).
 */
export type ScanProgress = {
	/**  The throttled, monotonic count of files seen so far. */
	scanned: number,
};

/**
 *  Why a dropped item was skipped — the four detection-INELIGIBLE §1.2 outcome classes (§0.6 / §1.3).
 *  Carried on `SkippedItem.reason` as the canonical skip cause. The `DetectionOutcome → SkipReason`
 *  projection is P2.16, and the ONE-WAY forward `SkipReason → ErrorKind` projection (the non-invertible
 *  `Uncertain → Unrecognized`, §2.8.2) lives on the §1.12 helper (P2.20), never on this type. NOT
 *  `ErrorKind`: a skip is a freeze-time ineligibility, distinct from a conversion-time failure.
 *
 *  [Build-Session-Entscheidung: P2.5] Mirrors the sibling fieldless wire enums (`ReadFailure` /
 *  `Confidence`): `Copy` (fieldless) + the uniform `#[serde(rename_all = "camelCase")]` wire form
 *  (`unsupportedType` / `uncertain` / `empty` / `unreadable`). No `Hash` (not a map key).
 */
export type SkipReason =
/**  A real type we identified but do not convert (the ineligible `DetectionOutcome::UnsupportedType`). */
"unsupportedType" |
/**  Sniffed but contradictory / below threshold — we declined to guess (`DetectionOutcome::Uncertain`). */
"uncertain" |
/**  0-byte / no bytes to read (`DetectionOutcome::Empty`). */
"empty" |
/**  Could not read the bytes at all (`DetectionOutcome::Unreadable`). */
"unreadable";

/**
 *  An item present in the drop but NOT eligible for the batch — unsupported / uncertain / empty /
 *  unreadable at the §1.1 freeze (§0.6 / §1.3). Surfaced in the §1.4 confirm summary and the §1.12 run
 *  summary so a bad item is never silently dropped. `item` is drawn from the SAME single id space as the
 *  eligible `DroppedItem`s but is **id-DISJOINT** with them (§0.6 invariant 6 — the eligible
 *  `members`/`items` and the `skipped` ids are never-re-indexed filtered VIEWS over one space, so a
 *  `SkippedItem.item` can never collide with an eligible id). It stores a `SkipReason` (NOT an
 *  `ErrorKind`): every `SkippedItem` comes from a detection-INELIGIBLE outcome, all of which have a
 *  `SkipReason`, so the §1.12 `OutcomeMsg::Skipped` projection is a trivial copy (no undefined
 *  `ErrorKind → SkipReason` reverse map at the boundary).
 *
 *  [Build-Session-Entscheidung: P2.5] Wire policy mirrors `DroppedItem` / the P2.2/P2.3/P2.15 §0.6
 *  types: derives `specta::Type` + `Serialize`/`Deserialize` with `#[serde(rename_all = "camelCase")]`.
 *  NOT `Copy` (owns a `PathBuf`); `PartialEq`+`Eq` back the round-trip + §6 property tests. No explicit
 *  specta registration — auto-registers via its consuming command (the C1 `CollectedSet` return, P2.22).
 */
export type SkippedItem = {
	/**
	 *  The §0.6 invariant-6 freeze-assigned id — id-disjoint with the eligible items over the single id
	 *  space (never re-indexed from 0). Symmetric with `DroppedItem.item`.
	 */
	item: ItemId,
	/**  The dropped path, for the §1.4 summary display. */
	source: string,
	/**  Why the item was skipped — a §0.6 `SkipReason`, NOT an `ErrorKind` (see the type doc). */
	reason: SkipReason,
};

/**  A UI surface tier for an option (§1.6) — Basic (materially changes a normal result) vs Advanced. */
export type Surface =
/**  The few switches that materially change a normal user's result. */
"basic" |
/**  Power-user knobs, hidden by default. */
"advanced";

/**
 *  An offered output choice for a source (§0.6 / §1.5). `lossy` is the §1.5 offer-time SINGLE
 *  predictable-loss marker (`Option<LossyKind>`, ≤1); the §2.9.2 co-applying render-set (2-3 kinds) is a
 *  SEPARATE render-time computation (P4.65), not this field.
 */
export type Target = {
	/**  The target identity (e.g. `Format(Webp)` | `Op(ExtractAudio)` | `Op(ToGif)`). */
	id: TargetId,
	/**  The display label. */
	label: string,
	/**  The §1.5 offer-time single predictable-loss marker (§2.9 catalog key; the string lives in §2.9). */
	lossy: LossyKind | null,
	/**  Per-platform availability (from §3.4). */
	availability: Availability,
	/**  The §1.6 declared options model (concrete values in 04-formats). */
	options: OptionDecl[],
};

/**  The offered-target identity (§0.6 / §1.5): a format target or a cross-category operation. */
export type TargetId =
/**  A format target (e.g. `Format(Webp)`). */
({ format: UserFacingFormat }) & { op?: never } |
/**  A cross-category operation (`ExtractAudio` | `ToGif`). */
({ op: CrossCatOp }) & { format?: never };

/**
 *  The C3 `get_targets` return (§0.6 / §1.5) — the offered targets for a collected set plus the
 *  exactly-one pre-highlighted default.
 */
export type TargetOffer = {
	/**  The collected set these targets are offered for. */
	set: CollectedSetId,
	/**  The offered targets. */
	targets: Target[],
	/**  Exactly ONE pre-highlighted default (§1.5). */
	defaultTarget: TargetId,
};

/**
 *  The §1.12 per-outcome tally (§0.6). The "all failed" condition is DERIVED (`all_failed()`), never a
 *  stored field — SSOT *Fail clearly*: a fully-failed batch is an explicit failure, not a quiet finish.
 *
 *  [Build-Session-Entscheidung: P2.12] `Serialize` + `Type` (wire — embedded in `RunResult`), NO
 *  `Deserialize`; NOT `Copy` (the §0.6 struct convention, cf. `PreflightVerdict`). camelCase. The
 *  `total()`/`all_failed()` helpers home the §1.12 derived condition so it is computed once, never
 *  re-derived inconsistently (and never stored as a field).
 */
export type Totals = {
	/**  Items that converted + published successfully (§2.1). */
	succeeded: number,
	/**  Items that failed with a named §2.8 kind (the batch continued, §1.9). */
	failed: number,
	/**  Items discarded by user cancel (§1.7/§1.11) — finished-before-cancel items stay in `succeeded`. */
	cancelled: number,
	/**  Pre-flight detection-ineligible items projected into the summary (§1.3/§1.12) — never `failed`. */
	skipped: number,
};

/**  Display unit for an `IntRange` option — purely for the §5 label, not semantic (§1.6). */
export type Unit = "percent" | "kbps" | "px" | "dpi" | "fps";

/**
 *  The single grouping key (§1.3): an individual user-facing format — NOT the six SSOT categories,
 *  NOT codec subtypes (`Jpg != Png`, `Mp4 != Mov`). The enumeration IS the SSOT *What It Converts*
 *  set; `04-formats/` owns each one's detection signature / targets / engine / options — this enum is
 *  just the key. Two dropped items group into one batch iff their `UserFacingFormat` is equal (§1.3).
 *
 *  [Build-Session-Entscheidung: P2.3] `#[serde(rename_all = "camelCase")]` per the §0.6 "camelCase on
 *  the wire" rule + the sibling `ErrorKind`/`IntakeOrigin` precedent (each variant lowercases its
 *  leading letter: `jpg`/`png`/…/`threeGp`/…/`odp`). Derive set: `PartialEq`+`Eq`+`Hash` because this
 *  is the §1.3 grouping/de-dup key; `Serialize`+`Deserialize`+`Type` because it crosses the wire both
 *  ways (the `CollectedSet`/`DetectionOutcome` returns outbound and the `FormatId = UserFacingFormat`
 *  C3+ target arg inbound, §0.6); `Copy` is free for a fieldless enum.
 */
export type UserFacingFormat = "jpg" | "png" | "webp" | "gif" | "bmp" | "tiff" | "heic" | "avif" | "ico" | "svg" | "mp3" | "wav" | "flac" | "aac" | "m4a" | "ogg" | "opus" | "wma" | "aiff" | "alac" | "mp4" | "mov" | "mkv" | "webm" | "avi" | "wmv" | "flv" | "mpeg" | "m4v" | "threeGp" | "pdf" | "docx" | "doc" | "odt" | "rtf" | "txt" | "md" | "html" | "xlsx" | "xls" | "ods" | "csv" | "tsv" | "pptx" | "ppt" | "odp";
