#!/usr/bin/env python3
"""g24-core-deps.py - G24 self-test for check-core-deps (P0.3.7, T6/G53).

Proves the core-crate forbidden-dependency walk: a forbidden image-worker C lib (libvips/libheif/
librsvg/libimagequant) anywhere in the MIT core's transitive closure is caught; a clean closure passes;
a core crate absent from the metadata returns None (cannot-evaluate). Drives the pure walk against
synthetic `cargo metadata` JSON (no cargo needed), confirms the tests/g53-fixture/ negative fixture is
structurally present + planted, and - when cargo is installed (P1) - runs the REAL fixture through
`cargo metadata --locked` and asserts the planted libvips-sys dep is flagged. stdlib-only.

The fixture's Cargo.lock is COMMITTED: `crate::untrusted_byte_boundary` reads it on every `cargo test`
(its armed canary), so every clone must carry it. It was once gitignored and created only as a side effect
of this self-test's `cargo metadata`, so a fresh clone's `cargo test` redded until the canary had run, and
CI stayed green only because its canary step runs before its `cargo test` step. The lock legs pin that
state: the lock is tracked and not ignored (the incident replayed in a throwaway repo), it is path-only
(never a real dependency lock), and the live resolve is `--locked` (it can neither create nor rewrite the
lock, so it can no longer mask a missing or stale one). [Build-Session-Entscheidung: P0.3.7] committed,
not generated by the Rust test: a test that spawned cargo to lock a copy would tie every `cargo test` (and
every cargo-mutants mutant) to a working cargo resolve, while the committed lock is a fixed input under the
L(-1) cage (tests/g53-fixture/**).
Exit 0 = all held; 1 = a self-test failed.
"""
import importlib.machinery
import importlib.util
import json
import os
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path
for _stream in (sys.stdout, sys.stderr):          # the console's codepage is not this script's concern (G9 invariant i)
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8", errors="replace")
# A git hook exports GIT_* variables (an absolute GIT_DIR in a linked worktree): under them, a git run from this
# file in a temp directory - its own, a gate's or a tool's - acts on the hooked repository. All but GIT_EXEC_PATH go.
for _k in [k for k in os.environ if k.startswith("GIT_") and k != "GIT_EXEC_PATH"]:
    os.environ.pop(_k)

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "check-core-deps"
FIXTURE = ROOT / "tests" / "g53-fixture"
_loader = importlib.machinery.SourceFileLoader("ccd", str(SCRIPT))
m = importlib.util.module_from_spec(importlib.util.spec_from_loader("ccd", _loader))
_loader.exec_module(m)

results: list[tuple[str, bool]] = []


def record(name: str, ok: bool) -> None:
    results.append((name, ok))
    print(f"[{'PASS' if ok else 'FAIL'}] {name}")


def meta(*edges: tuple[str, str], names: tuple[str, ...]) -> dict:
    """Build a synthetic `cargo metadata` dict: `names` are the packages, `edges` are (from, to) dep
    links (by name). Ids are 'NAME 0.0.0'."""
    pid = lambda n: f"{n} 0.0.0"
    packages = [{"id": pid(n), "name": n} for n in names]
    nodes = {n: {"id": pid(n), "deps": []} for n in names}
    for frm, to in edges:
        nodes[frm]["deps"].append({"pkg": pid(to)})
    return {"packages": packages, "resolve": {"nodes": list(nodes.values())}}


# --- pure closure walk ------------------------------------------------------------------------
violation = meta(("convertia-core", "libvips-sys"), names=("convertia-core", "libvips-sys"))
record("core -> libvips-sys in closure -> forbidden hit",
       m.forbidden_in_closure(m.core_closure(violation)) == ["libvips-sys"])

transitive = meta(("convertia-core", "img-helper"), ("img-helper", "libheif-sys"),
                  names=("convertia-core", "img-helper", "libheif-sys"))
record("TRANSITIVE core -> img-helper -> libheif-sys -> caught (full closure, not just direct deps)",
       m.forbidden_in_closure(m.core_closure(transitive)) == ["libheif-sys"])

clean = meta(("convertia-core", "serde"), ("serde", "serde_derive"),
             names=("convertia-core", "serde", "serde_derive"))
record("clean closure (serde only) -> no forbidden hit", m.forbidden_in_closure(m.core_closure(clean)) == [])

record("each forbidden binding (the §3.6.1 set) is caught",
       all(m.forbidden_in_closure({"convertia-core", dep}) == [dep] for dep in
           ("libvips-sys", "libheif-sys", "librsvg-sys", "libimagequant", "rsvg")))
record("libde265-sys (§3.6.1 LGPL HEVC decoder, paired with libheif) -> caught (G1 review P1 fix)",
       m.forbidden_in_closure({"convertia-core", "libde265-sys"}) == ["libde265-sys"])
record("an ImageMagick binding (magick-rust) -> caught (G1 review P2; image-worker delegate, §2.12)",
       m.forbidden_in_closure({"convertia-core", "magick-rust"}) == ["magick-rust"])

record("core crate ABSENT from metadata -> core_closure returns None (cannot-evaluate)",
       m.core_closure(meta(("a", "b"), names=("a", "b"))) is None)

record("the core crate itself is in its closure but is NOT a forbidden hit",
       "convertia-core" not in m.forbidden_in_closure(m.core_closure(clean)))

# --- the §0.8 flate2 backend selection (the feature plane) -------------------------------------
# The motivating incident, replayed verbatim: flate2 1.1.10's feature table + the ACTIVATED features and
# the resolve deps `cargo metadata --locked` reported on 2026-09-24 - `zlib-rs` is on the deps list (the
# weak `zlib-rs?/std` in `default` puts it into the lock) yet NOT activated. Each clause of the leg then
# gets a mutant-discriminating leg: read the deps list instead of the features -> the replay reds; drop the
# subset check -> the zlib-rs / libz-sys activations pass; count a weak `x?/feat` as an activation -> the
# replay reds; drop the missing-`rust_backend` guard -> that leg passes silently; drop the positive
# miniz_oxide requirement -> the re-pointed-`rust_backend` leg passes (the G1 review P1); treat a missing
# `features` record as "nothing activated" -> that leg passes.
FLATE2_1_1_10_TABLE = {
    "any_c_zlib": ["any_zlib"], "any_impl": [], "any_zlib": ["any_impl"], "cloudflare_zlib": ["zlib"],
    "default": ["rust_backend", "runtime_detection"], "document-features": ["dep:document-features"],
    "libz-ng-sys": ["dep:libz-ng-sys"], "libz-sys": ["dep:libz-sys"], "miniz-sys": ["rust_backend"],
    "miniz_oxide": ["any_impl", "dep:miniz_oxide", "dep:crc32fast"],
    "runtime_detection": ["zlib-rs?/std", "crc32fast?/std"], "rust_backend": ["miniz_oxide", "any_impl"],
    "zlib": ["any_c_zlib", "libz-sys", "dep:crc32fast"], "zlib-default": ["any_c_zlib", "libz-sys/default", "dep:crc32fast"],
    "zlib-ng": ["any_c_zlib", "libz-ng-sys", "dep:crc32fast"], "zlib-ng-compat": ["zlib", "libz-sys/zlib-ng", "dep:crc32fast"],
    "zlib-rs": ["any_zlib", "dep:zlib-rs"],
}
FLATE2_1_1_10_ACTIVATED = ["any_impl", "default", "miniz_oxide", "runtime_detection", "rust_backend"]
FLATE2_1_1_10_DEPS = ["crc32fast", "miniz_oxide", "zlib-rs"]
FLATE2_ID = "flate2 1.1.10"


def meta_flate2(activated: list[str], table: dict = FLATE2_1_1_10_TABLE, deps: list[str] = FLATE2_1_1_10_DEPS,
                in_closure: bool = True) -> dict:
    """A synthetic `cargo metadata` with the core, flate2 (its feature table + activated features + the
    resolve deps) and the crates it names; `in_closure=False` leaves flate2 out of the core's edges."""
    names = ["convertia-core", "png"] + deps
    packages = [{"id": f"{n} 0.0.0", "name": n} for n in names] + [{"id": FLATE2_ID, "name": "flate2", "features": table}]
    nodes = {p["id"]: {"id": p["id"], "deps": [], "features": []} for p in packages}
    nodes["convertia-core 0.0.0"]["deps"].append({"pkg": "png 0.0.0"})
    if in_closure:
        nodes["png 0.0.0"]["deps"].append({"pkg": FLATE2_ID})
    nodes[FLATE2_ID]["deps"] = [{"pkg": f"{d} 0.0.0"} for d in deps]
    nodes[FLATE2_ID]["features"] = list(activated)
    return {"packages": packages, "resolve": {"nodes": list(nodes.values())}}


def _f2(md: dict) -> tuple[list[str], list[str]]:
    return m.flate2_backend_problems(md, m.core_closure_ids(md) or set())


_replay = _f2(meta_flate2(FLATE2_1_1_10_ACTIVATED))
record("REPLAY 2026-09-24: flate2 1.1.10 with `zlib-rs` on its resolve deps but NOT activated -> clean, and "
       "the leg EVALUATED it (non-vacuous)", _replay == ([], [FLATE2_ID]))
_zrs = _f2(meta_flate2(FLATE2_1_1_10_ACTIVATED + ["zlib-rs"]))
record("flate2 with the `zlib-rs` feature ACTIVATED -> caught, naming zlib-rs",
       len(_zrs[0]) == 1 and "'zlib-rs'" in _zrs[0][0])
_czl = _f2(meta_flate2(["default", "zlib"], deps=FLATE2_1_1_10_DEPS + ["libz-sys"]))
record("flate2 with the C `zlib` feature ACTIVATED (libz-sys) -> caught, naming libz-sys",
       len(_czl[0]) == 1 and "'libz-sys'" in _czl[0][0])
_zdef = _f2(meta_flate2(["zlib-default"], deps=FLATE2_1_1_10_DEPS + ["libz-sys"]))
record("a `x/feat` entry (zlib-default -> libz-sys/default) counts as activating x -> caught (and, with "
       "miniz_oxide not turned on at all, that positive requirement fires beside it)",
       len(_zdef[0]) == 2 and any("'libz-sys'" in p for p in _zdef[0]) and any("do not turn on `miniz_oxide`" in p for p in _zdef[0]))
_norb = _f2(meta_flate2(FLATE2_1_1_10_ACTIVATED, table={k: v for k, v in FLATE2_1_1_10_TABLE.items() if k != "rust_backend"}))
record("a flate2 whose feature table has NO `rust_backend` -> fail-closed (cannot evaluate the selection)",
       len(_norb[0]) == 1 and "cannot be evaluated" in _norb[0][0])
record("flate2 OUTSIDE the core closure is not evaluated (no problem, nothing evaluated)",
       _f2(meta_flate2(FLATE2_1_1_10_ACTIVATED + ["zlib-rs"], in_closure=False)) == ([], []))
record("_feature_closure: the weak `x?/feat` form turns on nothing; `dep:x` and `x/feat` turn on x",
       m._feature_closure({"a": ["b?/std", "dep:c", "d/e"]}, {"a"}) == ({"a"}, {"c", "d"}))
_REPOINTED = {**FLATE2_1_1_10_TABLE, "rust_backend": ["zlib-rs", "any_impl"],
              "zlib-rs": ["any_zlib", "dep:zlib-rs", "miniz_oxide?/std"]}
_rp = _f2(meta_flate2(["any_impl", "any_zlib", "default", "runtime_detection", "rust_backend", "zlib-rs"],
                      table=_REPOINTED))
record("REVIEW P1 replay: a flate2 whose `rust_backend` is re-pointed at zlib-rs (miniz_oxide only weakly) "
       "-> caught, naming miniz_oxide (the row names the crate, not just the feature)",
       len(_rp[0]) == 1 and "no longer turns on `miniz_oxide`" in _rp[0][0])
_nofeat = meta_flate2(FLATE2_1_1_10_ACTIVATED)
for _n in _nofeat["resolve"]["nodes"]:
    if _n["id"] == FLATE2_ID:
        del _n["features"]
record("a flate2 resolve node WITHOUT a `features` record -> fail-closed (cannot evaluate), not \"nothing activated\"",
       any("no `features` record" in p for p in _f2(_nofeat)[0]))

# --- the fixture is structurally present + planted --------------------------------------------
core_toml = FIXTURE / "convertia-core" / "Cargo.toml"
record("tests/g53-fixture workspace + core + libvips-sys crates exist",
       (FIXTURE / "Cargo.toml").is_file() and core_toml.is_file()
       and (FIXTURE / "libvips-sys" / "Cargo.toml").is_file())
record("the fixture core crate declares the planted libvips-sys dependency",
       "libvips-sys" in core_toml.read_text(encoding="utf-8"))

# --- the committed fixture lock: tracked, not ignored, path-only ------------------------------
FIXTURE_LOCK_REL = "tests/g53-fixture/Cargo.lock"
PRE_FIX_IGNORE_RULE = "/tests/g53-fixture/Cargo.lock"   # the .gitignore line that kept the lock out of every clone


def lock_git_problems(repo: Path) -> list[str]:
    """What would keep the fixture lock out of a fresh clone of `repo`: it is not in the index (a clone
    never receives it), or an ignore rule matches it (`--no-index`, so a force-added lock that a rule
    still matches is reported too - the rule would drop it again on the next re-add). Fail-closed when
    git cannot answer."""
    def git(*args: str) -> int:
        return subprocess.run(["git", "-C", str(repo), *args], capture_output=True).returncode
    try:
        tracked = git("ls-files", "--error-unmatch", "--", FIXTURE_LOCK_REL)
        ignored = git("check-ignore", "-q", "--no-index", "--", FIXTURE_LOCK_REL)
    except OSError as exc:
        return [f"git could not be run ({exc}) - cannot prove the fixture lock is committed"]
    problems = []
    if tracked == 1:
        problems.append(f"{FIXTURE_LOCK_REL} is not tracked - a fresh clone has no fixture lock")
    elif tracked != 0:
        problems.append(f"`git ls-files` exited {tracked} - cannot prove the fixture lock is tracked")
    if ignored == 0:
        problems.append(f"{FIXTURE_LOCK_REL} matches an ignore rule")
    elif ignored != 1:
        problems.append(f"`git check-ignore` exited {ignored} - cannot prove the fixture lock is not ignored")
    return problems


def throwaway_repo(td: str, *, ignore_rule: bool, force_add: bool) -> Path:
    """A throwaway git repo holding a fixture lock at the real path, optionally under the pre-fix ignore
    rule and optionally force-added to the index."""
    repo = Path(td)
    subprocess.run(["git", "init", "-q", str(repo)], capture_output=True, check=True)
    lock = repo / FIXTURE_LOCK_REL
    lock.parent.mkdir(parents=True)
    lock.write_text("version = 4\n", encoding="utf-8", newline="\n")
    if ignore_rule:
        (repo / ".gitignore").write_text(PRE_FIX_IGNORE_RULE + "\n", encoding="utf-8", newline="\n")
    if force_add:
        subprocess.run(["git", "-C", str(repo), "add", "-f", "--", FIXTURE_LOCK_REL], capture_output=True, check=True)
    return repo


with tempfile.TemporaryDirectory() as td:
    _replay = lock_git_problems(throwaway_repo(td, ignore_rule=True, force_add=False))
record("REPLAY (the pre-fix tree): an untracked lock under the old `/tests/g53-fixture/Cargo.lock` ignore "
       "rule -> refused as both untracked and ignored",
       len(_replay) == 2 and "is not tracked" in _replay[0] and "matches an ignore rule" in _replay[1])
with tempfile.TemporaryDirectory() as td:
    _forced = lock_git_problems(throwaway_repo(td, ignore_rule=True, force_add=True))
record("a force-added lock that an ignore rule still matches -> refused as ignored only (`--no-index`)",
       len(_forced) == 1 and "matches an ignore rule" in _forced[0])
_real = lock_git_problems(ROOT)
record("this repo tracks tests/g53-fixture/Cargo.lock and no ignore rule matches it (every clone carries "
       "the lock `crate::untrusted_byte_boundary` reads)", _real == [])
for _p in _real:
    print(f"[g24-core-deps]   {_p}")

try:
    _lock_rows = tomllib.loads((FIXTURE / "Cargo.lock").read_text(encoding="utf-8")).get("package", [])
    _lock_pkgs = {row["name"]: row for row in _lock_rows}
except (OSError, UnicodeDecodeError, tomllib.TOMLDecodeError, KeyError, TypeError, AttributeError):
    _lock_rows, _lock_pkgs = [], {}
record("the committed fixture lock is path-only: exactly convertia-core + libvips-sys, the planted "
       "convertia-core -> libvips-sys edge, no registry `source` or `checksum` (never a real dependency lock)",
       len(_lock_rows) == 2 and set(_lock_pkgs) == {"convertia-core", "libvips-sys"}
       and _lock_pkgs["convertia-core"].get("dependencies") == ["libvips-sys"]
       and not any("source" in row or "checksum" in row for row in _lock_rows))

# --- regression guard (P1.12): the live `cargo metadata` read MUST pin encoding="utf-8" -------
# Once the tauri dep tree (~250 crates / ~900 KB metadata) landed, a non-ASCII byte in a crate
# description cp1252-crashed check-core-deps on Windows (text=True without encoding). main()'s skip
# path is covered by _skip_when_cargo_absent below + the live walk by the fixture leg below, so
# main() is NOT re-run live here (heavy + plane-dependent on a real cargo).
import inspect as _inspect
record("regression: check-core-deps' live `cargo metadata` read pins encoding=\"utf-8\" "
       "(a non-ASCII byte in the ~900 KB metadata must not cp1252-crash on Windows; P1.12)",
       'encoding="utf-8"' in _inspect.getsource(m.main))

# --- live: run the REAL fixture through `cargo metadata --locked` when cargo is installed (P1) --
def cargo_locked_metadata(manifest: Path) -> tuple[str, str]:
    """`cargo metadata --locked` over a fixture manifest -> ('ok', stdout) | ('stale', stderr) | ('env',
    stderr). `--locked` refuses to create or rewrite the lock, so a missing or stale committed lock is a
    verdict here, never a silent regeneration. The cwd is the repo root, so rustup resolves the pinned
    toolchain for a throwaway copy outside the tree as well."""
    proc = subprocess.run(
        ["cargo", "metadata", "--locked", "--format-version", "1", "--manifest-path", str(manifest)],
        cwd=str(ROOT), capture_output=True, text=True, encoding="utf-8", errors="replace")
    if proc.returncode == 0:
        return "ok", proc.stdout
    if "--locked was passed" in proc.stderr:     # cargo's refusal for both a stale and an absent lock
        return "stale", proc.stderr
    return "env", proc.stderr


if shutil.which("cargo"):
    _verdict, _out = cargo_locked_metadata(FIXTURE / "Cargo.toml")
    if _verdict == "env":
        print(f"[g24-core-deps] cargo present but `cargo metadata` on the fixture failed "
              f"(env) - skipping the live legs:\n{_out.strip()[:200]}")
    else:
        record("LIVE fixture: `cargo metadata --locked` accepts the committed lock and its core closure flags "
               "libvips-sys (a stale lock fails here: re-lock with `cargo metadata --manifest-path "
               "tests/g53-fixture/Cargo.toml` and commit the lock)",
               _verdict == "ok" and "libvips-sys" in m.forbidden_in_closure(m.core_closure(json.loads(_out)) or set()))
        if _verdict != "ok":
            print(f"[g24-core-deps]   {_out.strip()[:300]}")
        with tempfile.TemporaryDirectory() as td:
            _stale = Path(td) / "fixture"
            shutil.copytree(FIXTURE, _stale)
            _vips = _stale / "libvips-sys" / "Cargo.toml"
            _vips.write_text(_vips.read_text(encoding="utf-8").replace('version = "0.0.0"', 'version = "0.0.1"'),
                             encoding="utf-8", newline="\n")
            _stale_lock = _stale / "Cargo.lock"
            _lock_before = _stale_lock.read_bytes() if _stale_lock.is_file() else None
            _stale_verdict = cargo_locked_metadata(_stale / "Cargo.toml")[0]
            _lock_after = _stale_lock.read_bytes() if _stale_lock.is_file() else None
        record("a fixture copy whose manifests no longer match its lock -> refused as stale, the lock left "
               "byte-identical",
               _lock_before is not None and _stale_verdict == "stale" and _lock_after == _lock_before)
        with tempfile.TemporaryDirectory() as td:
            _bare = Path(td) / "fixture"
            shutil.copytree(FIXTURE, _bare)
            (_bare / "Cargo.lock").unlink(missing_ok=True)
            _bare_verdict = cargo_locked_metadata(_bare / "Cargo.toml")[0]
            _bare_created = (_bare / "Cargo.lock").exists()
        record("REPLAY (a clone without the lock): `--locked` refuses and creates no lock - this self-test can "
               "no longer generate the file `cargo test` reads and so hide its absence",
               _bare_verdict == "stale" and not _bare_created)
else:
    print("[g24-core-deps] cargo not installed - skipping the live fixture legs (P1 activates them)")

# --- the P1-runway fix: a Cargo manifest present but cargo absent in this plane -> SKIP (0), not the
# old hard FAIL (the live walk enforces at L1/L2 + the equipped Rust CI job; skip-here / enforce-there) -
def _skip_when_cargo_absent() -> int:
    import tempfile
    saved = (m.ROOT, m.CARGO_TOML_CANDIDATES, m.shutil.which)
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        (root / "Cargo.toml").write_text('[package]\nname = "x"\n', encoding="utf-8")
        m.ROOT = root
        m.CARGO_TOML_CANDIDATES = (root / "Cargo.toml", root / "src-tauri" / "Cargo.toml")
        m.shutil.which = lambda tool: None
        try:
            return m.main()
        finally:
            m.ROOT, m.CARGO_TOML_CANDIDATES, m.shutil.which = saved


record("main(): Cargo manifest present but cargo absent in this plane -> SKIP (0), not the old fail "
       "(P1-runway fix; the live walk enforces where cargo is present)",
       _skip_when_cargo_absent() == 0)

# --- main() WIRING (r4 review, P3): the pure legs above prove each clause; these prove main() ACTS on both
# branches (a disconnected `if hits:` / `if f2_problems:` would print OK and exit 0). `cargo metadata` is
# monkeypatched to return the synthetic metadata; the real Cargo.toml + a fake `cargo` on PATH drive main().
def _main_over(md: dict) -> int:
    saved = (m.shutil.which, m.subprocess.run)
    m.shutil.which = lambda tool: "cargo"
    m.subprocess.run = lambda *a, **k: subprocess.CompletedProcess(a, 0, stdout=json.dumps(md), stderr="")
    try:
        return m.main()
    finally:
        m.shutil.which, m.subprocess.run = saved


record("main(): the replayed flate2 1.1.10 metadata (zlib-rs on the deps, not activated) -> exit 0",
       _main_over(meta_flate2(FLATE2_1_1_10_ACTIVATED)) == 0)
record("main(): flate2 with `zlib-rs` ACTIVATED -> exit 1 (the flate2 branch is wired, not only pure)",
       _main_over(meta_flate2(["zlib-rs"])) == 1)
record("main(): libvips-sys in the core closure -> exit 1 (the forbidden-stem branch is wired)",
       _main_over(meta(("convertia-core", "libvips-sys"), names=("convertia-core", "libvips-sys"))) == 1)

failed = [n for n, ok in results if not ok]
print(f"\n[g24-core-deps] {len(results) - len(failed)}/{len(results)} assertions passed.")
sys.exit(1 if failed else 0)
