#!/usr/bin/env python3
"""g54-gate-plane.py - G24 self-test for the G54 gate-plane integrity check (P0.2.3).

Proves scripts/check-gate-plane FAILS on a broken plane and PASSES on an intact one,
in throwaway temp git repos. No real lefthook is needed: the check keys on the
'lefthook' marker string + file presence, so fixture hook files suffice. Temp repos
are auto-removed (tempfile.TemporaryDirectory).

Run:  python3 scripts/gate-selftests/g54-gate-plane.py
Exit: 0 = every assertion held; 1 = a self-test assertion FAILED (the gate is broken).
"""
import subprocess
import sys
import tempfile
from pathlib import Path

CHECK = Path(__file__).resolve().parents[2] / "scripts" / "check-gate-plane"
results: list[tuple[str, bool]] = []


def record(name: str, ok: bool, detail: str = "") -> None:
    results.append((name, ok))
    print(f"[{'PASS' if ok else 'FAIL'}] {name}{(' - ' + detail) if detail else ''}")


def git(repo: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "-C", str(repo), *args], capture_output=True, text=True)


def run_check(repo: Path, *extra: str) -> tuple[int, str]:
    p = subprocess.run([sys.executable, str(CHECK), *extra], capture_output=True, text=True, cwd=str(repo))
    return p.returncode, p.stdout + p.stderr


def write_hook(hooks_dir: Path, name: str, lefthook: bool = True) -> None:
    hooks_dir.mkdir(parents=True, exist_ok=True)
    # Harmless (exit 0) so git running the hook during the test's own commits never
    # interferes; the lefthook variant still carries the 'lefthook' marker the check keys on.
    body = ("#!/bin/sh\n# generated by lefthook\nexit 0\n" if lefthook
            else "#!/bin/sh\necho plain-hook\nexit 0\n")
    (hooks_dir / name).write_text(body, encoding="utf-8")


def setup_repo(td: str) -> Path:
    repo = Path(td) / "repo"
    repo.mkdir()
    git(repo, "init", "-q", "-b", "main")
    git(repo, "config", "user.email", "selftest@example.invalid")
    git(repo, "config", "user.name", "selftest")
    (repo / "f.txt").write_text("x", encoding="utf-8")
    git(repo, "add", "f.txt")
    git(repo, "commit", "-q", "-m", "A")
    return repo


# --- positive: lefthook-managed hooks present, no redirect ---
with tempfile.TemporaryDirectory() as td:
    repo = setup_repo(td)
    hd = repo / ".git" / "hooks"
    write_hook(hd, "pre-commit")
    write_hook(hd, "pre-push")
    rc, out = run_check(repo)
    record("intact plane passes", rc == 0, f"exit={rc}")

# --- negative: pre-commit missing ---
with tempfile.TemporaryDirectory() as td:
    repo = setup_repo(td)
    write_hook(repo / ".git" / "hooks", "pre-push")  # pre-commit absent
    rc, out = run_check(repo)
    record("missing pre-commit fails", rc == 1 and "missing" in out.lower(), f"exit={rc}")

# --- negative: a hook that is NOT lefthook-managed ---
with tempfile.TemporaryDirectory() as td:
    repo = setup_repo(td)
    hd = repo / ".git" / "hooks"
    write_hook(hd, "pre-commit", lefthook=False)
    write_hook(hd, "pre-push", lefthook=False)
    rc, out = run_check(repo)
    record("non-lefthook hook fails", rc == 1 and "not lefthook-managed" in out.lower(), f"exit={rc}")

# --- negative: core.hooksPath redirected to an empty dir (the silent-bypass case) ---
with tempfile.TemporaryDirectory() as td:
    repo = setup_repo(td)
    hd = repo / ".git" / "hooks"
    write_hook(hd, "pre-commit")
    write_hook(hd, "pre-push")  # real lefthook hooks exist...
    empty = Path(td) / "empty-hooks"
    empty.mkdir()
    git(repo, "config", "core.hooksPath", str(empty))  # ...but the plane is redirected away
    rc, out = run_check(repo)
    record("core.hooksPath redirect fails", rc == 1 and "hookspath" in out.lower(), f"exit={rc}")

# --- pre-push: fresh base passes, stale base fails ---
with tempfile.TemporaryDirectory() as td:
    repo = setup_repo(td)
    hd = repo / ".git" / "hooks"
    write_hook(hd, "pre-commit")
    write_hook(hd, "pre-push")
    head = git(repo, "rev-parse", "HEAD").stdout.strip()
    git(repo, "update-ref", "refs/remotes/origin/main", head)  # origin/main == HEAD
    rc, out = run_check(repo, "--pre-push")
    record("pre-push fresh base passes", rc == 0, f"exit={rc}")
    git(repo, "checkout", "-q", "-b", "other")
    git(repo, "commit", "-q", "--allow-empty", "-m", "B")
    other = git(repo, "rev-parse", "HEAD").stdout.strip()
    git(repo, "checkout", "-q", "main")
    git(repo, "update-ref", "refs/remotes/origin/main", other)  # origin/main diverged ahead
    rc, out = run_check(repo, "--pre-push")
    record("pre-push stale base fails", rc == 1 and "stale-base" in out.lower(), f"exit={rc}")

failed = [n for n, ok in results if not ok]
print(f"\n[g54-gate-plane] {len(results) - len(failed)}/{len(results)} assertions passed.")
sys.exit(1 if failed else 0)
